! <testinfo>
! test_generator=config/mercurium-fortran
! </testinfo>
SUBROUTINE S(X)
    INTEGER :: X

    IF (X == 1) THEN
        PRINT *, "X equals ", 1
    ELSE IF (X == 2) THEN
        PRINT *, "X equals ", 2
    ELSE IF (X == 3) THEN
        PRINT *, "X equals ", 3
    ELSE IF (X == 4) THEN
        PRINT *, "X equals ", 4
    ELSE IF (X == 5) THEN
        PRINT *, "X equals ", 5
    ELSE IF (X == 6) THEN
        PRINT *, "X equals ", 6
    ELSE IF (X == 7) THEN
        PRINT *, "X equals ", 7
    ELSE IF (X == 8) THEN
        PRINT *, "X equals ", 8
    ELSE IF (X == 9) THEN
        PRINT *, "X equals ", 9
    ELSE IF (X == 10) THEN
        PRINT *, "X equals ", 10
    ELSE IF (X == 11) THEN
        PRINT *, "X equals ", 11
    ELSE IF (X == 12) THEN
        PRINT *, "X equals ", 12
    ELSE IF (X == 13) THEN
        PRINT *, "X equals ", 13
    ELSE IF (X == 14) THEN
        PRINT *, "X equals ", 14
    ELSE IF (X == 15) THEN
        PRINT *, "X equals ", 15
    ELSE IF (X == 16) THEN
        PRINT *, "X equals ", 16
    ELSE IF (X == 17) THEN
        PRINT *, "X equals ", 17
    ELSE IF (X == 18) THEN
        PRINT *, "X equals ", 18
    ELSE IF (X == 19) THEN
        PRINT *, "X equals ", 19
    ELSE IF (X == 20) THEN
        PRINT *, "X equals ", 20
    ELSE IF (X == 21) THEN
        PRINT *, "X equals ", 21
    ELSE IF (X == 22) THEN
        PRINT *, "X equals ", 22
    ELSE IF (X == 23) THEN
        PRINT *, "X equals ", 23
    ELSE IF (X == 24) THEN
        PRINT *, "X equals ", 24
    ELSE IF (X == 25) THEN
        PRINT *, "X equals ", 25
    ELSE IF (X == 26) THEN
        PRINT *, "X equals ", 26
    ELSE IF (X == 27) THEN
        PRINT *, "X equals ", 27
    ELSE IF (X == 28) THEN
        PRINT *, "X equals ", 28
    ELSE IF (X == 29) THEN
        PRINT *, "X equals ", 29
    ELSE IF (X == 30) THEN
        PRINT *, "X equals ", 30
    ELSE IF (X == 31) THEN
        PRINT *, "X equals ", 31
    ELSE IF (X == 32) THEN
        PRINT *, "X equals ", 32
    ELSE IF (X == 33) THEN
        PRINT *, "X equals ", 33
    ELSE IF (X == 34) THEN
        PRINT *, "X equals ", 34
    ELSE IF (X == 35) THEN
        PRINT *, "X equals ", 35
    ELSE IF (X == 36) THEN
        PRINT *, "X equals ", 36
    ELSE IF (X == 37) THEN
        PRINT *, "X equals ", 37
    ELSE IF (X == 38) THEN
        PRINT *, "X equals ", 38
    ELSE IF (X == 39) THEN
        PRINT *, "X equals ", 39
    ELSE IF (X == 40) THEN
        PRINT *, "X equals ", 40
    ELSE IF (X == 41) THEN
        PRINT *, "X equals ", 41
    ELSE IF (X == 42) THEN
        PRINT *, "X equals ", 42
    ELSE IF (X == 43) THEN
        PRINT *, "X equals ", 43
    ELSE IF (X == 44) THEN
        PRINT *, "X equals ", 44
    ELSE IF (X == 45) THEN
        PRINT *, "X equals ", 45
    ELSE IF (X == 46) THEN
        PRINT *, "X equals ", 46
    ELSE IF (X == 47) THEN
        PRINT *, "X equals ", 47
    ELSE IF (X == 48) THEN
        PRINT *, "X equals ", 48
    ELSE IF (X == 49) THEN
        PRINT *, "X equals ", 49
    ELSE IF (X == 50) THEN
        PRINT *, "X equals ", 50
    ELSE IF (X == 51) THEN
        PRINT *, "X equals ", 51
    ELSE IF (X == 52) THEN
        PRINT *, "X equals ", 52
    ELSE IF (X == 53) THEN
        PRINT *, "X equals ", 53
    ELSE IF (X == 54) THEN
        PRINT *, "X equals ", 54
    ELSE IF (X == 55) THEN
        PRINT *, "X equals ", 55
    ELSE IF (X == 56) THEN
        PRINT *, "X equals ", 56
    ELSE IF (X == 57) THEN
        PRINT *, "X equals ", 57
    ELSE IF (X == 58) THEN
        PRINT *, "X equals ", 58
    ELSE IF (X == 59) THEN
        PRINT *, "X equals ", 59
    ELSE IF (X == 60) THEN
        PRINT *, "X equals ", 60
    ELSE IF (X == 61) THEN
        PRINT *, "X equals ", 61
    ELSE IF (X == 62) THEN
        PRINT *, "X equals ", 62
    ELSE IF (X == 63) THEN
        PRINT *, "X equals ", 63
    ELSE IF (X == 64) THEN
        PRINT *, "X equals ", 64
    ELSE IF (X == 65) THEN
        PRINT *, "X equals ", 65
    ELSE IF (X == 66) THEN
        PRINT *, "X equals ", 66
    ELSE IF (X == 67) THEN
        PRINT *, "X equals ", 67
    ELSE IF (X == 68) THEN
        PRINT *, "X equals ", 68
    ELSE IF (X == 69) THEN
        PRINT *, "X equals ", 69
    ELSE IF (X == 70) THEN
        PRINT *, "X equals ", 70
    ELSE IF (X == 71) THEN
        PRINT *, "X equals ", 71
    ELSE IF (X == 72) THEN
        PRINT *, "X equals ", 72
    ELSE IF (X == 73) THEN
        PRINT *, "X equals ", 73
    ELSE IF (X == 74) THEN
        PRINT *, "X equals ", 74
    ELSE IF (X == 75) THEN
        PRINT *, "X equals ", 75
    ELSE IF (X == 76) THEN
        PRINT *, "X equals ", 76
    ELSE IF (X == 77) THEN
        PRINT *, "X equals ", 77
    ELSE IF (X == 78) THEN
        PRINT *, "X equals ", 78
    ELSE IF (X == 79) THEN
        PRINT *, "X equals ", 79
    ELSE IF (X == 80) THEN
        PRINT *, "X equals ", 80
    ELSE IF (X == 81) THEN
        PRINT *, "X equals ", 81
    ELSE IF (X == 82) THEN
        PRINT *, "X equals ", 82
    ELSE IF (X == 83) THEN
        PRINT *, "X equals ", 83
    ELSE IF (X == 84) THEN
        PRINT *, "X equals ", 84
    ELSE IF (X == 85) THEN
        PRINT *, "X equals ", 85
    ELSE IF (X == 86) THEN
        PRINT *, "X equals ", 86
    ELSE IF (X == 87) THEN
        PRINT *, "X equals ", 87
    ELSE IF (X == 88) THEN
        PRINT *, "X equals ", 88
    ELSE IF (X == 89) THEN
        PRINT *, "X equals ", 89
    ELSE IF (X == 90) THEN
        PRINT *, "X equals ", 90
    ELSE IF (X == 91) THEN
        PRINT *, "X equals ", 91
    ELSE IF (X == 92) THEN
        PRINT *, "X equals ", 92
    ELSE IF (X == 93) THEN
        PRINT *, "X equals ", 93
    ELSE IF (X == 94) THEN
        PRINT *, "X equals ", 94
    ELSE IF (X == 95) THEN
        PRINT *, "X equals ", 95
    ELSE IF (X == 96) THEN
        PRINT *, "X equals ", 96
    ELSE IF (X == 97) THEN
        PRINT *, "X equals ", 97
    ELSE IF (X == 98) THEN
        PRINT *, "X equals ", 98
    ELSE IF (X == 99) THEN
        PRINT *, "X equals ", 99
    ELSE IF (X == 100) THEN
        PRINT *, "X equals ", 100
    ELSE IF (X == 101) THEN
        PRINT *, "X equals ", 101
    ELSE IF (X == 102) THEN
        PRINT *, "X equals ", 102
    ELSE IF (X == 103) THEN
        PRINT *, "X equals ", 103
    ELSE IF (X == 104) THEN
        PRINT *, "X equals ", 104
    ELSE IF (X == 105) THEN
        PRINT *, "X equals ", 105
    ELSE IF (X == 106) THEN
        PRINT *, "X equals ", 106
    ELSE IF (X == 107) THEN
        PRINT *, "X equals ", 107
    ELSE IF (X == 108) THEN
        PRINT *, "X equals ", 108
    ELSE IF (X == 109) THEN
        PRINT *, "X equals ", 109
    ELSE IF (X == 110) THEN
        PRINT *, "X equals ", 110
    ELSE IF (X == 111) THEN
        PRINT *, "X equals ", 111
    ELSE IF (X == 112) THEN
        PRINT *, "X equals ", 112
    ELSE IF (X == 113) THEN
        PRINT *, "X equals ", 113
    ELSE IF (X == 114) THEN
        PRINT *, "X equals ", 114
    ELSE IF (X == 115) THEN
        PRINT *, "X equals ", 115
    ELSE IF (X == 116) THEN
        PRINT *, "X equals ", 116
    ELSE IF (X == 117) THEN
        PRINT *, "X equals ", 117
    ELSE IF (X == 118) THEN
        PRINT *, "X equals ", 118
    ELSE IF (X == 119) THEN
        PRINT *, "X equals ", 119
    ELSE IF (X == 120) THEN
        PRINT *, "X equals ", 120
    ELSE IF (X == 121) THEN
        PRINT *, "X equals ", 121
    ELSE IF (X == 122) THEN
        PRINT *, "X equals ", 122
    ELSE IF (X == 123) THEN
        PRINT *, "X equals ", 123
    ELSE IF (X == 124) THEN
        PRINT *, "X equals ", 124
    ELSE IF (X == 125) THEN
        PRINT *, "X equals ", 125
    ELSE IF (X == 126) THEN
        PRINT *, "X equals ", 126
    ELSE IF (X == 127) THEN
        PRINT *, "X equals ", 127
    ELSE IF (X == 128) THEN
        PRINT *, "X equals ", 128
    ELSE IF (X == 129) THEN
        PRINT *, "X equals ", 129
    ELSE IF (X == 130) THEN
        PRINT *, "X equals ", 130
    ELSE IF (X == 131) THEN
        PRINT *, "X equals ", 131
    ELSE IF (X == 132) THEN
        PRINT *, "X equals ", 132
    ELSE IF (X == 133) THEN
        PRINT *, "X equals ", 133
    ELSE IF (X == 134) THEN
        PRINT *, "X equals ", 134
    ELSE IF (X == 135) THEN
        PRINT *, "X equals ", 135
    ELSE IF (X == 136) THEN
        PRINT *, "X equals ", 136
    ELSE IF (X == 137) THEN
        PRINT *, "X equals ", 137
    ELSE IF (X == 138) THEN
        PRINT *, "X equals ", 138
    ELSE IF (X == 139) THEN
        PRINT *, "X equals ", 139
    ELSE IF (X == 140) THEN
        PRINT *, "X equals ", 140
    ELSE IF (X == 141) THEN
        PRINT *, "X equals ", 141
    ELSE IF (X == 142) THEN
        PRINT *, "X equals ", 142
    ELSE IF (X == 143) THEN
        PRINT *, "X equals ", 143
    ELSE IF (X == 144) THEN
        PRINT *, "X equals ", 144
    ELSE IF (X == 145) THEN
        PRINT *, "X equals ", 145
    ELSE IF (X == 146) THEN
        PRINT *, "X equals ", 146
    ELSE IF (X == 147) THEN
        PRINT *, "X equals ", 147
    ELSE IF (X == 148) THEN
        PRINT *, "X equals ", 148
    ELSE IF (X == 149) THEN
        PRINT *, "X equals ", 149
    ELSE IF (X == 150) THEN
        PRINT *, "X equals ", 150
    ELSE IF (X == 151) THEN
        PRINT *, "X equals ", 151
    ELSE IF (X == 152) THEN
        PRINT *, "X equals ", 152
    ELSE IF (X == 153) THEN
        PRINT *, "X equals ", 153
    ELSE IF (X == 154) THEN
        PRINT *, "X equals ", 154
    ELSE IF (X == 155) THEN
        PRINT *, "X equals ", 155
    ELSE IF (X == 156) THEN
        PRINT *, "X equals ", 156
    ELSE IF (X == 157) THEN
        PRINT *, "X equals ", 157
    ELSE IF (X == 158) THEN
        PRINT *, "X equals ", 158
    ELSE IF (X == 159) THEN
        PRINT *, "X equals ", 159
    ELSE IF (X == 160) THEN
        PRINT *, "X equals ", 160
    ELSE IF (X == 161) THEN
        PRINT *, "X equals ", 161
    ELSE IF (X == 162) THEN
        PRINT *, "X equals ", 162
    ELSE IF (X == 163) THEN
        PRINT *, "X equals ", 163
    ELSE IF (X == 164) THEN
        PRINT *, "X equals ", 164
    ELSE IF (X == 165) THEN
        PRINT *, "X equals ", 165
    ELSE IF (X == 166) THEN
        PRINT *, "X equals ", 166
    ELSE IF (X == 167) THEN
        PRINT *, "X equals ", 167
    ELSE IF (X == 168) THEN
        PRINT *, "X equals ", 168
    ELSE IF (X == 169) THEN
        PRINT *, "X equals ", 169
    ELSE IF (X == 170) THEN
        PRINT *, "X equals ", 170
    ELSE IF (X == 171) THEN
        PRINT *, "X equals ", 171
    ELSE IF (X == 172) THEN
        PRINT *, "X equals ", 172
    ELSE IF (X == 173) THEN
        PRINT *, "X equals ", 173
    ELSE IF (X == 174) THEN
        PRINT *, "X equals ", 174
    ELSE IF (X == 175) THEN
        PRINT *, "X equals ", 175
    ELSE IF (X == 176) THEN
        PRINT *, "X equals ", 176
    ELSE IF (X == 177) THEN
        PRINT *, "X equals ", 177
    ELSE IF (X == 178) THEN
        PRINT *, "X equals ", 178
    ELSE IF (X == 179) THEN
        PRINT *, "X equals ", 179
    ELSE IF (X == 180) THEN
        PRINT *, "X equals ", 180
    ELSE IF (X == 181) THEN
        PRINT *, "X equals ", 181
    ELSE IF (X == 182) THEN
        PRINT *, "X equals ", 182
    ELSE IF (X == 183) THEN
        PRINT *, "X equals ", 183
    ELSE IF (X == 184) THEN
        PRINT *, "X equals ", 184
    ELSE IF (X == 185) THEN
        PRINT *, "X equals ", 185
    ELSE IF (X == 186) THEN
        PRINT *, "X equals ", 186
    ELSE IF (X == 187) THEN
        PRINT *, "X equals ", 187
    ELSE IF (X == 188) THEN
        PRINT *, "X equals ", 188
    ELSE IF (X == 189) THEN
        PRINT *, "X equals ", 189
    ELSE IF (X == 190) THEN
        PRINT *, "X equals ", 190
    ELSE IF (X == 191) THEN
        PRINT *, "X equals ", 191
    ELSE IF (X == 192) THEN
        PRINT *, "X equals ", 192
    ELSE IF (X == 193) THEN
        PRINT *, "X equals ", 193
    ELSE IF (X == 194) THEN
        PRINT *, "X equals ", 194
    ELSE IF (X == 195) THEN
        PRINT *, "X equals ", 195
    ELSE IF (X == 196) THEN
        PRINT *, "X equals ", 196
    ELSE IF (X == 197) THEN
        PRINT *, "X equals ", 197
    ELSE IF (X == 198) THEN
        PRINT *, "X equals ", 198
    ELSE IF (X == 199) THEN
        PRINT *, "X equals ", 199
    ELSE IF (X == 200) THEN
        PRINT *, "X equals ", 200
    ELSE IF (X == 201) THEN
        PRINT *, "X equals ", 201
    ELSE IF (X == 202) THEN
        PRINT *, "X equals ", 202
    ELSE IF (X == 203) THEN
        PRINT *, "X equals ", 203
    ELSE IF (X == 204) THEN
        PRINT *, "X equals ", 204
    ELSE IF (X == 205) THEN
        PRINT *, "X equals ", 205
    ELSE IF (X == 206) THEN
        PRINT *, "X equals ", 206
    ELSE IF (X == 207) THEN
        PRINT *, "X equals ", 207
    ELSE IF (X == 208) THEN
        PRINT *, "X equals ", 208
    ELSE IF (X == 209) THEN
        PRINT *, "X equals ", 209
    ELSE IF (X == 210) THEN
        PRINT *, "X equals ", 210
    ELSE IF (X == 211) THEN
        PRINT *, "X equals ", 211
    ELSE IF (X == 212) THEN
        PRINT *, "X equals ", 212
    ELSE IF (X == 213) THEN
        PRINT *, "X equals ", 213
    ELSE IF (X == 214) THEN
        PRINT *, "X equals ", 214
    ELSE IF (X == 215) THEN
        PRINT *, "X equals ", 215
    ELSE IF (X == 216) THEN
        PRINT *, "X equals ", 216
    ELSE IF (X == 217) THEN
        PRINT *, "X equals ", 217
    ELSE IF (X == 218) THEN
        PRINT *, "X equals ", 218
    ELSE IF (X == 219) THEN
        PRINT *, "X equals ", 219
    ELSE IF (X == 220) THEN
        PRINT *, "X equals ", 220
    ELSE IF (X == 221) THEN
        PRINT *, "X equals ", 221
    ELSE IF (X == 222) THEN
        PRINT *, "X equals ", 222
    ELSE IF (X == 223) THEN
        PRINT *, "X equals ", 223
    ELSE IF (X == 224) THEN
        PRINT *, "X equals ", 224
    ELSE IF (X == 225) THEN
        PRINT *, "X equals ", 225
    ELSE IF (X == 226) THEN
        PRINT *, "X equals ", 226
    ELSE IF (X == 227) THEN
        PRINT *, "X equals ", 227
    ELSE IF (X == 228) THEN
        PRINT *, "X equals ", 228
    ELSE IF (X == 229) THEN
        PRINT *, "X equals ", 229
    ELSE IF (X == 230) THEN
        PRINT *, "X equals ", 230
    ELSE IF (X == 231) THEN
        PRINT *, "X equals ", 231
    ELSE IF (X == 232) THEN
        PRINT *, "X equals ", 232
    ELSE IF (X == 233) THEN
        PRINT *, "X equals ", 233
    ELSE IF (X == 234) THEN
        PRINT *, "X equals ", 234
    ELSE IF (X == 235) THEN
        PRINT *, "X equals ", 235
    ELSE IF (X == 236) THEN
        PRINT *, "X equals ", 236
    ELSE IF (X == 237) THEN
        PRINT *, "X equals ", 237
    ELSE IF (X == 238) THEN
        PRINT *, "X equals ", 238
    ELSE IF (X == 239) THEN
        PRINT *, "X equals ", 239
    ELSE IF (X == 240) THEN
        PRINT *, "X equals ", 240
    ELSE IF (X == 241) THEN
        PRINT *, "X equals ", 241
    ELSE IF (X == 242) THEN
        PRINT *, "X equals ", 242
    ELSE IF (X == 243) THEN
        PRINT *, "X equals ", 243
    ELSE IF (X == 244) THEN
        PRINT *, "X equals ", 244
    ELSE IF (X == 245) THEN
        PRINT *, "X equals ", 245
    ELSE IF (X == 246) THEN
        PRINT *, "X equals ", 246
    ELSE IF (X == 247) THEN
        PRINT *, "X equals ", 247
    ELSE IF (X == 248) THEN
        PRINT *, "X equals ", 248
    ELSE IF (X == 249) THEN
        PRINT *, "X equals ", 249
    ELSE IF (X == 250) THEN
        PRINT *, "X equals ", 250
    ELSE IF (X == 251) THEN
        PRINT *, "X equals ", 251
    ELSE IF (X == 252) THEN
        PRINT *, "X equals ", 252
    ELSE IF (X == 253) THEN
        PRINT *, "X equals ", 253
    ELSE IF (X == 254) THEN
        PRINT *, "X equals ", 254
    ELSE IF (X == 255) THEN
        PRINT *, "X equals ", 255
    ELSE IF (X == 256) THEN
        PRINT *, "X equals ", 256
    ELSE IF (X == 257) THEN
        PRINT *, "X equals ", 257
    ELSE IF (X == 258) THEN
        PRINT *, "X equals ", 258
    ELSE IF (X == 259) THEN
        PRINT *, "X equals ", 259
    ELSE IF (X == 260) THEN
        PRINT *, "X equals ", 260
    ELSE IF (X == 261) THEN
        PRINT *, "X equals ", 261
    ELSE IF (X == 262) THEN
        PRINT *, "X equals ", 262
    ELSE IF (X == 263) THEN
        PRINT *, "X equals ", 263
    ELSE IF (X == 264) THEN
        PRINT *, "X equals ", 264
    ELSE IF (X == 265) THEN
        PRINT *, "X equals ", 265
    ELSE IF (X == 266) THEN
        PRINT *, "X equals ", 266
    ELSE IF (X == 267) THEN
        PRINT *, "X equals ", 267
    ELSE IF (X == 268) THEN
        PRINT *, "X equals ", 268
    ELSE IF (X == 269) THEN
        PRINT *, "X equals ", 269
    ELSE IF (X == 270) THEN
        PRINT *, "X equals ", 270
    ELSE IF (X == 271) THEN
        PRINT *, "X equals ", 271
    ELSE IF (X == 272) THEN
        PRINT *, "X equals ", 272
    ELSE IF (X == 273) THEN
        PRINT *, "X equals ", 273
    ELSE IF (X == 274) THEN
        PRINT *, "X equals ", 274
    ELSE IF (X == 275) THEN
        PRINT *, "X equals ", 275
    ELSE IF (X == 276) THEN
        PRINT *, "X equals ", 276
    ELSE IF (X == 277) THEN
        PRINT *, "X equals ", 277
    ELSE IF (X == 278) THEN
        PRINT *, "X equals ", 278
    ELSE IF (X == 279) THEN
        PRINT *, "X equals ", 279
    ELSE IF (X == 280) THEN
        PRINT *, "X equals ", 280
    ELSE IF (X == 281) THEN
        PRINT *, "X equals ", 281
    ELSE IF (X == 282) THEN
        PRINT *, "X equals ", 282
    ELSE IF (X == 283) THEN
        PRINT *, "X equals ", 283
    ELSE IF (X == 284) THEN
        PRINT *, "X equals ", 284
    ELSE IF (X == 285) THEN
        PRINT *, "X equals ", 285
    ELSE IF (X == 286) THEN
        PRINT *, "X equals ", 286
    ELSE IF (X == 287) THEN
        PRINT *, "X equals ", 287
    ELSE IF (X == 288) THEN
        PRINT *, "X equals ", 288
    ELSE IF (X == 289) THEN
        PRINT *, "X equals ", 289
    ELSE IF (X == 290) THEN
        PRINT *, "X equals ", 290
    ELSE IF (X == 291) THEN
        PRINT *, "X equals ", 291
    ELSE IF (X == 292) THEN
        PRINT *, "X equals ", 292
    ELSE IF (X == 293) THEN
        PRINT *, "X equals ", 293
    ELSE IF (X == 294) THEN
        PRINT *, "X equals ", 294
    ELSE IF (X == 295) THEN
        PRINT *, "X equals ", 295
    ELSE IF (X == 296) THEN
        PRINT *, "X equals ", 296
    ELSE IF (X == 297) THEN
        PRINT *, "X equals ", 297
    ELSE IF (X == 298) THEN
        PRINT *, "X equals ", 298
    ELSE IF (X == 299) THEN
        PRINT *, "X equals ", 299
    ELSE IF (X == 300) THEN
        PRINT *, "X equals ", 300
    ELSE IF (X == 301) THEN
        PRINT *, "X equals ", 301
    ELSE IF (X == 302) THEN
        PRINT *, "X equals ", 302
    ELSE IF (X == 303) THEN
        PRINT *, "X equals ", 303
    ELSE IF (X == 304) THEN
        PRINT *, "X equals ", 304
    ELSE IF (X == 305) THEN
        PRINT *, "X equals ", 305
    ELSE IF (X == 306) THEN
        PRINT *, "X equals ", 306
    ELSE IF (X == 307) THEN
        PRINT *, "X equals ", 307
    ELSE IF (X == 308) THEN
        PRINT *, "X equals ", 308
    ELSE IF (X == 309) THEN
        PRINT *, "X equals ", 309
    ELSE IF (X == 310) THEN
        PRINT *, "X equals ", 310
    ELSE IF (X == 311) THEN
        PRINT *, "X equals ", 311
    ELSE IF (X == 312) THEN
        PRINT *, "X equals ", 312
    ELSE IF (X == 313) THEN
        PRINT *, "X equals ", 313
    ELSE IF (X == 314) THEN
        PRINT *, "X equals ", 314
    ELSE IF (X == 315) THEN
        PRINT *, "X equals ", 315
    ELSE IF (X == 316) THEN
        PRINT *, "X equals ", 316
    ELSE IF (X == 317) THEN
        PRINT *, "X equals ", 317
    ELSE IF (X == 318) THEN
        PRINT *, "X equals ", 318
    ELSE IF (X == 319) THEN
        PRINT *, "X equals ", 319
    ELSE IF (X == 320) THEN
        PRINT *, "X equals ", 320
    ELSE IF (X == 321) THEN
        PRINT *, "X equals ", 321
    ELSE IF (X == 322) THEN
        PRINT *, "X equals ", 322
    ELSE IF (X == 323) THEN
        PRINT *, "X equals ", 323
    ELSE IF (X == 324) THEN
        PRINT *, "X equals ", 324
    ELSE IF (X == 325) THEN
        PRINT *, "X equals ", 325
    ELSE IF (X == 326) THEN
        PRINT *, "X equals ", 326
    ELSE IF (X == 327) THEN
        PRINT *, "X equals ", 327
    ELSE IF (X == 328) THEN
        PRINT *, "X equals ", 328
    ELSE IF (X == 329) THEN
        PRINT *, "X equals ", 329
    ELSE IF (X == 330) THEN
        PRINT *, "X equals ", 330
    ELSE IF (X == 331) THEN
        PRINT *, "X equals ", 331
    ELSE IF (X == 332) THEN
        PRINT *, "X equals ", 332
    ELSE IF (X == 333) THEN
        PRINT *, "X equals ", 333
    ELSE IF (X == 334) THEN
        PRINT *, "X equals ", 334
    ELSE IF (X == 335) THEN
        PRINT *, "X equals ", 335
    ELSE IF (X == 336) THEN
        PRINT *, "X equals ", 336
    ELSE IF (X == 337) THEN
        PRINT *, "X equals ", 337
    ELSE IF (X == 338) THEN
        PRINT *, "X equals ", 338
    ELSE IF (X == 339) THEN
        PRINT *, "X equals ", 339
    ELSE IF (X == 340) THEN
        PRINT *, "X equals ", 340
    ELSE IF (X == 341) THEN
        PRINT *, "X equals ", 341
    ELSE IF (X == 342) THEN
        PRINT *, "X equals ", 342
    ELSE IF (X == 343) THEN
        PRINT *, "X equals ", 343
    ELSE IF (X == 344) THEN
        PRINT *, "X equals ", 344
    ELSE IF (X == 345) THEN
        PRINT *, "X equals ", 345
    ELSE IF (X == 346) THEN
        PRINT *, "X equals ", 346
    ELSE IF (X == 347) THEN
        PRINT *, "X equals ", 347
    ELSE IF (X == 348) THEN
        PRINT *, "X equals ", 348
    ELSE IF (X == 349) THEN
        PRINT *, "X equals ", 349
    ELSE IF (X == 350) THEN
        PRINT *, "X equals ", 350
    ELSE IF (X == 351) THEN
        PRINT *, "X equals ", 351
    ELSE IF (X == 352) THEN
        PRINT *, "X equals ", 352
    ELSE IF (X == 353) THEN
        PRINT *, "X equals ", 353
    ELSE IF (X == 354) THEN
        PRINT *, "X equals ", 354
    ELSE IF (X == 355) THEN
        PRINT *, "X equals ", 355
    ELSE IF (X == 356) THEN
        PRINT *, "X equals ", 356
    ELSE IF (X == 357) THEN
        PRINT *, "X equals ", 357
    ELSE IF (X == 358) THEN
        PRINT *, "X equals ", 358
    ELSE IF (X == 359) THEN
        PRINT *, "X equals ", 359
    ELSE IF (X == 360) THEN
        PRINT *, "X equals ", 360
    ELSE IF (X == 361) THEN
        PRINT *, "X equals ", 361
    ELSE IF (X == 362) THEN
        PRINT *, "X equals ", 362
    ELSE IF (X == 363) THEN
        PRINT *, "X equals ", 363
    ELSE IF (X == 364) THEN
        PRINT *, "X equals ", 364
    ELSE IF (X == 365) THEN
        PRINT *, "X equals ", 365
    ELSE IF (X == 366) THEN
        PRINT *, "X equals ", 366
    ELSE IF (X == 367) THEN
        PRINT *, "X equals ", 367
    ELSE IF (X == 368) THEN
        PRINT *, "X equals ", 368
    ELSE IF (X == 369) THEN
        PRINT *, "X equals ", 369
    ELSE IF (X == 370) THEN
        PRINT *, "X equals ", 370
    ELSE IF (X == 371) THEN
        PRINT *, "X equals ", 371
    ELSE IF (X == 372) THEN
        PRINT *, "X equals ", 372
    ELSE IF (X == 373) THEN
        PRINT *, "X equals ", 373
    ELSE IF (X == 374) THEN
        PRINT *, "X equals ", 374
    ELSE IF (X == 375) THEN
        PRINT *, "X equals ", 375
    ELSE IF (X == 376) THEN
        PRINT *, "X equals ", 376
    ELSE IF (X == 377) THEN
        PRINT *, "X equals ", 377
    ELSE IF (X == 378) THEN
        PRINT *, "X equals ", 378
    ELSE IF (X == 379) THEN
        PRINT *, "X equals ", 379
    ELSE IF (X == 380) THEN
        PRINT *, "X equals ", 380
    ELSE IF (X == 381) THEN
        PRINT *, "X equals ", 381
    ELSE IF (X == 382) THEN
        PRINT *, "X equals ", 382
    ELSE IF (X == 383) THEN
        PRINT *, "X equals ", 383
    ELSE IF (X == 384) THEN
        PRINT *, "X equals ", 384
    ELSE IF (X == 385) THEN
        PRINT *, "X equals ", 385
    ELSE IF (X == 386) THEN
        PRINT *, "X equals ", 386
    ELSE IF (X == 387) THEN
        PRINT *, "X equals ", 387
    ELSE IF (X == 388) THEN
        PRINT *, "X equals ", 388
    ELSE IF (X == 389) THEN
        PRINT *, "X equals ", 389
    ELSE IF (X == 390) THEN
        PRINT *, "X equals ", 390
    ELSE IF (X == 391) THEN
        PRINT *, "X equals ", 391
    ELSE IF (X == 392) THEN
        PRINT *, "X equals ", 392
    ELSE IF (X == 393) THEN
        PRINT *, "X equals ", 393
    ELSE IF (X == 394) THEN
        PRINT *, "X equals ", 394
    ELSE IF (X == 395) THEN
        PRINT *, "X equals ", 395
    ELSE IF (X == 396) THEN
        PRINT *, "X equals ", 396
    ELSE IF (X == 397) THEN
        PRINT *, "X equals ", 397
    ELSE IF (X == 398) THEN
        PRINT *, "X equals ", 398
    ELSE IF (X == 399) THEN
        PRINT *, "X equals ", 399
    ELSE IF (X == 400) THEN
        PRINT *, "X equals ", 400
    ELSE IF (X == 401) THEN
        PRINT *, "X equals ", 401
    ELSE IF (X == 402) THEN
        PRINT *, "X equals ", 402
    ELSE IF (X == 403) THEN
        PRINT *, "X equals ", 403
    ELSE IF (X == 404) THEN
        PRINT *, "X equals ", 404
    ELSE IF (X == 405) THEN
        PRINT *, "X equals ", 405
    ELSE IF (X == 406) THEN
        PRINT *, "X equals ", 406
    ELSE IF (X == 407) THEN
        PRINT *, "X equals ", 407
    ELSE IF (X == 408) THEN
        PRINT *, "X equals ", 408
    ELSE IF (X == 409) THEN
        PRINT *, "X equals ", 409
    ELSE IF (X == 410) THEN
        PRINT *, "X equals ", 410
    ELSE IF (X == 411) THEN
        PRINT *, "X equals ", 411
    ELSE IF (X == 412) THEN
        PRINT *, "X equals ", 412
    ELSE IF (X == 413) THEN
        PRINT *, "X equals ", 413
    ELSE IF (X == 414) THEN
        PRINT *, "X equals ", 414
    ELSE IF (X == 415) THEN
        PRINT *, "X equals ", 415
    ELSE IF (X == 416) THEN
        PRINT *, "X equals ", 416
    ELSE IF (X == 417) THEN
        PRINT *, "X equals ", 417
    ELSE IF (X == 418) THEN
        PRINT *, "X equals ", 418
    ELSE IF (X == 419) THEN
        PRINT *, "X equals ", 419
    ELSE IF (X == 420) THEN
        PRINT *, "X equals ", 420
    ELSE IF (X == 421) THEN
        PRINT *, "X equals ", 421
    ELSE IF (X == 422) THEN
        PRINT *, "X equals ", 422
    ELSE IF (X == 423) THEN
        PRINT *, "X equals ", 423
    ELSE IF (X == 424) THEN
        PRINT *, "X equals ", 424
    ELSE IF (X == 425) THEN
        PRINT *, "X equals ", 425
    ELSE IF (X == 426) THEN
        PRINT *, "X equals ", 426
    ELSE IF (X == 427) THEN
        PRINT *, "X equals ", 427
    ELSE IF (X == 428) THEN
        PRINT *, "X equals ", 428
    ELSE IF (X == 429) THEN
        PRINT *, "X equals ", 429
    ELSE IF (X == 430) THEN
        PRINT *, "X equals ", 430
    ELSE IF (X == 431) THEN
        PRINT *, "X equals ", 431
    ELSE IF (X == 432) THEN
        PRINT *, "X equals ", 432
    ELSE IF (X == 433) THEN
        PRINT *, "X equals ", 433
    ELSE IF (X == 434) THEN
        PRINT *, "X equals ", 434
    ELSE IF (X == 435) THEN
        PRINT *, "X equals ", 435
    ELSE IF (X == 436) THEN
        PRINT *, "X equals ", 436
    ELSE IF (X == 437) THEN
        PRINT *, "X equals ", 437
    ELSE IF (X == 438) THEN
        PRINT *, "X equals ", 438
    ELSE IF (X == 439) THEN
        PRINT *, "X equals ", 439
    ELSE IF (X == 440) THEN
        PRINT *, "X equals ", 440
    ELSE IF (X == 441) THEN
        PRINT *, "X equals ", 441
    ELSE IF (X == 442) THEN
        PRINT *, "X equals ", 442
    ELSE IF (X == 443) THEN
        PRINT *, "X equals ", 443
    ELSE IF (X == 444) THEN
        PRINT *, "X equals ", 444
    ELSE IF (X == 445) THEN
        PRINT *, "X equals ", 445
    ELSE IF (X == 446) THEN
        PRINT *, "X equals ", 446
    ELSE IF (X == 447) THEN
        PRINT *, "X equals ", 447
    ELSE IF (X == 448) THEN
        PRINT *, "X equals ", 448
    ELSE IF (X == 449) THEN
        PRINT *, "X equals ", 449
    ELSE IF (X == 450) THEN
        PRINT *, "X equals ", 450
    ELSE IF (X == 451) THEN
        PRINT *, "X equals ", 451
    ELSE IF (X == 452) THEN
        PRINT *, "X equals ", 452
    ELSE IF (X == 453) THEN
        PRINT *, "X equals ", 453
    ELSE IF (X == 454) THEN
        PRINT *, "X equals ", 454
    ELSE IF (X == 455) THEN
        PRINT *, "X equals ", 455
    ELSE IF (X == 456) THEN
        PRINT *, "X equals ", 456
    ELSE IF (X == 457) THEN
        PRINT *, "X equals ", 457
    ELSE IF (X == 458) THEN
        PRINT *, "X equals ", 458
    ELSE IF (X == 459) THEN
        PRINT *, "X equals ", 459
    ELSE IF (X == 460) THEN
        PRINT *, "X equals ", 460
    ELSE IF (X == 461) THEN
        PRINT *, "X equals ", 461
    ELSE IF (X == 462) THEN
        PRINT *, "X equals ", 462
    ELSE IF (X == 463) THEN
        PRINT *, "X equals ", 463
    ELSE IF (X == 464) THEN
        PRINT *, "X equals ", 464
    ELSE IF (X == 465) THEN
        PRINT *, "X equals ", 465
    ELSE IF (X == 466) THEN
        PRINT *, "X equals ", 466
    ELSE IF (X == 467) THEN
        PRINT *, "X equals ", 467
    ELSE IF (X == 468) THEN
        PRINT *, "X equals ", 468
    ELSE IF (X == 469) THEN
        PRINT *, "X equals ", 469
    ELSE IF (X == 470) THEN
        PRINT *, "X equals ", 470
    ELSE IF (X == 471) THEN
        PRINT *, "X equals ", 471
    ELSE IF (X == 472) THEN
        PRINT *, "X equals ", 472
    ELSE IF (X == 473) THEN
        PRINT *, "X equals ", 473
    ELSE IF (X == 474) THEN
        PRINT *, "X equals ", 474
    ELSE IF (X == 475) THEN
        PRINT *, "X equals ", 475
    ELSE IF (X == 476) THEN
        PRINT *, "X equals ", 476
    ELSE IF (X == 477) THEN
        PRINT *, "X equals ", 477
    ELSE IF (X == 478) THEN
        PRINT *, "X equals ", 478
    ELSE IF (X == 479) THEN
        PRINT *, "X equals ", 479
    ELSE IF (X == 480) THEN
        PRINT *, "X equals ", 480
    ELSE IF (X == 481) THEN
        PRINT *, "X equals ", 481
    ELSE IF (X == 482) THEN
        PRINT *, "X equals ", 482
    ELSE IF (X == 483) THEN
        PRINT *, "X equals ", 483
    ELSE IF (X == 484) THEN
        PRINT *, "X equals ", 484
    ELSE IF (X == 485) THEN
        PRINT *, "X equals ", 485
    ELSE IF (X == 486) THEN
        PRINT *, "X equals ", 486
    ELSE IF (X == 487) THEN
        PRINT *, "X equals ", 487
    ELSE IF (X == 488) THEN
        PRINT *, "X equals ", 488
    ELSE IF (X == 489) THEN
        PRINT *, "X equals ", 489
    ELSE IF (X == 490) THEN
        PRINT *, "X equals ", 490
    ELSE IF (X == 491) THEN
        PRINT *, "X equals ", 491
    ELSE IF (X == 492) THEN
        PRINT *, "X equals ", 492
    ELSE IF (X == 493) THEN
        PRINT *, "X equals ", 493
    ELSE IF (X == 494) THEN
        PRINT *, "X equals ", 494
    ELSE IF (X == 495) THEN
        PRINT *, "X equals ", 495
    ELSE IF (X == 496) THEN
        PRINT *, "X equals ", 496
    ELSE IF (X == 497) THEN
        PRINT *, "X equals ", 497
    ELSE IF (X == 498) THEN
        PRINT *, "X equals ", 498
    ELSE IF (X == 499) THEN
        PRINT *, "X equals ", 499
    ELSE IF (X == 500) THEN
        PRINT *, "X equals ", 500
    ELSE
        PRINT *, "X equals something else"
    END IF
END

