! <testinfo>
! test_generator="config/mercurium-fortran run"
! </testinfo>
SUBROUTINE FOO(DUMMY_PROCEDURE)
    INTERFACE
        SUBROUTINE MY_FUN()
            IMPLICIT NONE
        END SUBROUTINE
    END INTERFACE

    PROCEDURE(MY_FUN) :: DUMMY_PROCEDURE
    PROCEDURE(MY_FUN) :: EXTERNAL_PROCEDURE
    PROCEDURE(MY_FUN), POINTER :: POINTER_PROCEDURE1 => NULL()
    PROCEDURE(MY_FUN), POINTER :: POINTER_PROCEDURE2 => NULL()
    PROCEDURE(MY_FUN), POINTER :: POINTER_PROCEDURE3 => NULL()

    POINTER_PROCEDURE1 => DUMMY_PROCEDURE
    POINTER_PROCEDURE2 => EXTERNAL_PROCEDURE

    POINTER_PROCEDURE3 => POINTER_PROCEDURE1

    CALL DUMMY_PROCEDURE()
    CALL EXTERNAL_PROCEDURE()
    CALL POINTER_PROCEDURE1()
    CALL POINTER_PROCEDURE2()
    CALL POINTER_PROCEDURE3()

END SUBROUTINE FOO

PROGRAM P
    IMPLICIT NONE

    INTERFACE
        SUBROUTINE BAR()
        IMPLICIT NONE
        END SUBROUTINE BAR
    END INTERFACE

    CALL FOO(BAR)
END PROGRAM P

SUBROUTINE BAR()
    IMPLICIT NONE
    PRINT *, "BAR!"
END SUBROUTINE BAR

SUBROUTINE EXTERNAL_PROCEDURE()
    IMPLICIT NONE
    PRINT *, "EXTERNAL_PROCEDURE"
END SUBROUTINE EXTERNAL_PROCEDURE
