! <testinfo>
! test_generator=config/mercurium-fortran
! </testinfo>
      INTEGER FUNCTION FF324(NINT, IDON03)
!          THIS FUNCTION IS USED BY TESTS 029, 030 AND 031 OF MAIN
!     PROGRAM FM317 TO TEST THE ASSOCIATION OF EXTERNAL FUNCTION AND
!     INTRINSIC FUNCTION NAMES USED AS ACTUAL ARGUMENTS TO A PROCEDURE
!     NAME USED AS A DUMMY ARGUMENT.  THIS FUNCTION REFERENCES THE
!     EXTERNAL FUNCTION OR INTRINSIC FUNCTION PASSED AS A PROCEDURE
!     NAME ARGUMENT, INCREMENTING THE RESULT BY ONE BEFORE RETURNING
!     THE RESULT AS THE FUNCTION VALUE.
      FF324 = NINT(IDON03) + 1
!          **** THE NAME NINT IS A DUMMY ARGUMENT
!                   AND NOT AN INTRINSIC FUNCTION REFERENCE *****
      END
