! <testinfo>
! test_generator=config/mercurium-fortran
! compile_versions="mod mod2 use all"
! test_FFLAGS_mod="-DWRITE_MOD"
! test_FFLAGS_mod2="-DWRITE_MOD2"
! test_FFLAGS_use="-DUSE_MOD"
! test_FFLAGS_all="-DWRITE_MOD -DWRITE_MOD2 -DUSE_MOD"
! </testinfo>

#ifdef WRITE_MOD
MODULE M
  IMPLICIT NONE

 INTERFACE FOO
   MODULE PROCEDURE FOO
   MODULE PROCEDURE FOO2
 END INTERFACE FOO

CONTAINS

  SUBROUTINE FOO(X)
    IMPLICIT NONE
    INTEGER :: X
  END SUBROUTINE FOO

  SUBROUTINE FOO2(X)
    IMPLICIT NONE
    REAL :: X
  END SUBROUTINE FOO2

END MODULE M
#endif

#ifdef WRITE_MOD2
MODULE M2
  IMPLICIT NONE

 INTERFACE FOO
   MODULE PROCEDURE FOO3
 END INTERFACE FOO

CONTAINS

  SUBROUTINE FOO3(X)
    IMPLICIT NONE
    COMPLEX :: X
  END SUBROUTINE FOO3

END MODULE M2
#endif

#ifdef USE_MOD
PROGRAM MAIN
    USE M
    USE M2
    IMPLICIT NONE

    CALL FOO(1)
    CALL FOO(1.2)
    CALL FOO((1.2, 3.4))
END PROGRAM MAIN
#endif
