! <testinfo>
! test_generator="config/mercurium-fortran run"
! </testinfo>
SUBROUTINE FOO(F1)
    USE ISO_C_BINDING
    IMPLICIT NONE
    INTERFACE
        SUBROUTINE MY_C_FUN() BIND(C)
          USE ISO_C_BINDING
          IMPLICIT NONE
        END SUBROUTINE MY_C_FUN
    END INTERFACE
    PROCEDURE(MY_C_FUN) :: F1
    PROCEDURE(F1), POINTER :: F2
    PROCEDURE(F2), POINTER :: F3 => NULL()
    TYPE(C_FUNPTR) :: CPTR1, CPTR2, CPTR3

    F2 => F1
    CALL F2()

    CPTR1 = C_FUNLOC(F1)
    CPTR2 = C_FUNLOC(F2)
    CPTR3 = C_FUNLOC(F3)
END SUBROUTINE FOO

PROGRAM P
    IMPLICIT NONE

    INTERFACE
        SUBROUTINE MY_C_FUN()
            IMPLICIT NONE
        END SUBROUTINE MY_C_FUN
    END INTERFACE

    CALL FOO(MY_C_FUN)
END PROGRAM P

SUBROUTINE MY_C_FUN()
    PRINT *, "MY_C_FUN"
END SUBROUTINE
