#ifndef PRESCANNER_IDENTIFIER_H
#define PRESCANNER_IDENTIFIER_H

#include "prescanner-process.h"

enum language_level_t {
	LANG_TOP_LEVEL = 0,
	LANG_DECLARATION_PART = 1,
	LANG_INSTRUCTION_PART = 2
};

typedef enum language_level_t language_level;

language_level convert_line(prescanner_t* prescanner, language_level previous, char** line, int num_line);

enum statement_type_t {
	ST_ASSIGNMENT = 1,
	ST_TYPEDECL,
	ST_TYPESPEC,
	ST_INITIALIZATION,
	ST_PROGRAM,
	ST_SUBROUTINE,
	ST_FUNCTION,
	ST_DUBIOUS_FUNCTION,
	ST_MODULE,
	ST_MODULE_PROCEDURE,
	ST_BLOCKDATA,
	ST_USE,
	ST_IMPLICIT,
	ST_PARAMETER,
	ST_FORMAT,
	ST_ENTRY,
	ST_ACCESS,
	ST_ALLOCATABLE,
	ST_COMMON,
	ST_DATA,
	ST_DIMENSION,
	ST_EQUIVALENCE,
	ST_EXTERNAL,
	ST_INTENT,
	ST_INTRINSIC,
	ST_NAMELIST,
	ST_OPTIONAL,
	ST_POINTER,
	ST_SAVE,
	ST_VALUE,
	ST_VOLATILE,
	ST_TARGET,
	ST_DO,
	ST_LABELED_DO,
	ST_FORALL,
	ST_ARITHMETIC_IF,
	ST_IF,
	ST_IF_STMT,
	ST_WHERE,
	ST_ALLOCATE,
	ST_BACKSPACE,
	ST_CALL,
	ST_CLOSE,
	ST_CONTINUE,
	ST_CYCLE,
	ST_DEALLOCATE,
	ST_ENDFILE,
	ST_EXIT,
	ST_GOTO,
	ST_LABEL_ASSIGN,
	ST_INQUIRE,
	ST_NULLIFY,
	ST_OPEN,
	ST_PRINT,
	ST_READ,
	ST_RETURN,
	ST_REWIND,
	ST_PAUSE,
	ST_STOP,
	ST_WRITE,
	ST_INTERFACE,
	ST_ELSE,
	ST_ELSEIF,
	ST_SELECTCASE,
	ST_CASE,
	ST_END,
	DC_INCLUDE
};

typedef enum statement_type_t statement_type;

#endif // PRESCANNER_IDENTIFIER_H
