load_lib target.exp

set full_path_tool "$BUILD_DIR/$tool"
set testcases [lsort [find $srcdir/$subdir *.cpp]]

foreach test $testcases {
    set basename_test [file tail $test]
    set kind_of_test ""
    if [string match "success_*" $basename_test] {
        set kind_of_test "success"
    } elseif [string match "failure_*" $basename_test] {
        set kind_of_test "xfailure"
    } else {
        unresolved "$test"
        continue
    }

    send_user "Running test ${basename_test}...\n"

    set output_execution ""
    if {
        [catch { 
            set output_execution [exec "$full_path_tool" "-y" "--debug-flag=print_scope_brief" "$test" "|&" "cat"] 
        } output_execution ]
    } {
        if [expr { $kind_of_test == "xfailure" }] {
            pass "$test"
        } elseif [expr {$kind_of_test == "success"}] {
            fail "$test"
        } 
        send_log "${output_execution}\n"
    } else {
        if [expr { $kind_of_test == "success" }] {
            pass "$test"
        } elseif [expr { $kind_of_test == "xfailure"} ] {
            xpass "$test"
        }
    }
}
