void __kmpc_atomic_fixed1_add( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_add_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_add( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_andb( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_andb_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_andl( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_andl_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_div( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_div_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
int8_t __kmpc_atomic_fixed1_div_rev_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_div( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_div( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_div_rev( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_eqv( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_eqv_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_max( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_max_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_min( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_min_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_mul( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_mul_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_mul( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_mul( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_neqv( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_neqv_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_orb( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_orb_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_orl( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_orl_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_rd( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_shl( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_shl_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
int8_t __kmpc_atomic_fixed1_shl_rev_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_shl_rev( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_shr( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_shr_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
int8_t __kmpc_atomic_fixed1_shr_rev_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_shr_rev( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_sub( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_sub_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
int8_t __kmpc_atomic_fixed1_sub_rev_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1_sub( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_sub_rev( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_swp( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_wr( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
void __kmpc_atomic_fixed1_xor( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs);
int8_t __kmpc_atomic_fixed1_xor_cpt( ident_t* id_ref, int gtid, int8_t *lhs, int8_t rhs, int flag);
void __kmpc_atomic_fixed1u_div( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs);
uint8_t __kmpc_atomic_fixed1u_div_cpt( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs, int flag);
uint8_t __kmpc_atomic_fixed1u_div_rev_cpt( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs, int flag);
void __kmpc_atomic_fixed1u_div( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs);
void __kmpc_atomic_fixed1u_div_rev( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs);
void __kmpc_atomic_fixed1u_shr( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs);
uint8_t __kmpc_atomic_fixed1u_shr_cpt( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs, int flag);
uint8_t __kmpc_atomic_fixed1u_shr_rev_cpt( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs, int flag);
void __kmpc_atomic_fixed1u_shr_rev( ident_t* id_ref, int gtid, uint8_t *lhs, uint8_t rhs);
void __kmpc_atomic_fixed2_add( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_add_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_add( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_andb( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_andb_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_andl( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_andl_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_div( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_div_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
int16_t __kmpc_atomic_fixed2_div_rev_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_div( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_div( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_div_rev( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_eqv( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_eqv_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_max( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_max_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_min( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_min_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_mul( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_mul_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_mul( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_mul( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_neqv( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_neqv_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_orb( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_orb_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_orl( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_orl_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_rd( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_shl( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_shl_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
int16_t __kmpc_atomic_fixed2_shl_rev_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_shl_rev( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_shr( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_shr_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
int16_t __kmpc_atomic_fixed2_shr_rev_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_shr_rev( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_sub( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_sub_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
int16_t __kmpc_atomic_fixed2_sub_rev_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2_sub( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_sub_rev( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_swp( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_wr( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
void __kmpc_atomic_fixed2_xor( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs);
int16_t __kmpc_atomic_fixed2_xor_cpt( ident_t* id_ref, int gtid, int16_t *lhs, int16_t rhs, int flag);
void __kmpc_atomic_fixed2u_div( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs);
uint16_t __kmpc_atomic_fixed2u_div_cpt( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs, int flag);
uint16_t __kmpc_atomic_fixed2u_div_rev_cpt( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs, int flag);
void __kmpc_atomic_fixed2u_div( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs);
void __kmpc_atomic_fixed2u_div_rev( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs);
void __kmpc_atomic_fixed2u_shr( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs);
uint16_t __kmpc_atomic_fixed2u_shr_cpt( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs, int flag);
uint16_t __kmpc_atomic_fixed2u_shr_rev_cpt( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs, int flag);
void __kmpc_atomic_fixed2u_shr_rev( ident_t* id_ref, int gtid, uint16_t *lhs, uint16_t rhs);
void __kmpc_atomic_fixed4_add( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_add_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_add( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_andb( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_andb_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_andl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_andl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_div_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed4_div_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_div_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_eqv( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_eqv_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_max( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_max_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_min( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_min_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_mul_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_neqv( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_neqv_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_orb( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_orb_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_orl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_orl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_rd( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_shl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_shl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed4_shl_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_shl_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_shr( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_shr_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed4_shr_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_shr_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_sub( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_sub_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed4_sub_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4_sub( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_sub_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_swp( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_wr( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed4_xor( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed4_xor_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed4u_div( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
uint32_t __kmpc_atomic_fixed4u_div_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
uint32_t __kmpc_atomic_fixed4u_div_rev_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
void __kmpc_atomic_fixed4u_div( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_fixed4u_div_rev( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_fixed4u_shr( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
uint32_t __kmpc_atomic_fixed4u_shr_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
uint32_t __kmpc_atomic_fixed4u_shr_rev_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
void __kmpc_atomic_fixed4u_shr_rev( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_fixed8_add( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_add_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_add( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_andb( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_andb_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_andl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_andl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_div_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed8_div_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_div( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_div_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_eqv( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_eqv_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_max( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_max_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_min( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_min_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_mul_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_mul( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_neqv( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_neqv_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_orb( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_orb_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_orl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_orl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_rd( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_shl( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_shl_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed8_shl_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_shl_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_shr( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_shr_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed8_shr_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_shr_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_sub( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_sub_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
int32_t __kmpc_atomic_fixed8_sub_rev_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8_sub( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_sub_rev( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_swp( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_wr( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
void __kmpc_atomic_fixed8_xor( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs);
int32_t __kmpc_atomic_fixed8_xor_cpt( ident_t* id_ref, int gtid, int32_t *lhs, int32_t rhs, int flag);
void __kmpc_atomic_fixed8u_div( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
uint32_t __kmpc_atomic_fixed8u_div_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
uint32_t __kmpc_atomic_fixed8u_div_rev_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
void __kmpc_atomic_fixed8u_div( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_fixed8u_div_rev( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_fixed8u_shr( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
uint32_t __kmpc_atomic_fixed8u_shr_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
uint32_t __kmpc_atomic_fixed8u_shr_rev_cpt( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs, int flag);
void __kmpc_atomic_fixed8u_shr_rev( ident_t* id_ref, int gtid, uint32_t *lhs, uint32_t rhs);
void __kmpc_atomic_float4_add( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_add_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_add( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_add( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_div( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_div_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
float __kmpc_atomic_float4_div_rev_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_div( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_div( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_div_rev( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_max( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_max_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_min( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_min_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_mul( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_mul_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_mul( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_mul( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_rd( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_sub( ident_t* id_ref, int gtid, float *lhs, float rhs);
float __kmpc_atomic_float4_sub_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
float __kmpc_atomic_float4_sub_rev_cpt( ident_t* id_ref, int gtid, float *lhs, float rhs, int flag);
void __kmpc_atomic_float4_sub( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_sub( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_sub_rev( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_swp( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float4_wr( ident_t* id_ref, int gtid, float *lhs, float rhs);
void __kmpc_atomic_float8_add( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_add_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_add( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_div( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_div_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
double __kmpc_atomic_float8_div_rev_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_div( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_div_rev( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_max( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_max_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_min( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_min_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_mul( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_mul_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_mul( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_rd( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_sub( ident_t* id_ref, int gtid, double *lhs, double rhs);
double __kmpc_atomic_float8_sub_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
double __kmpc_atomic_float8_sub_rev_cpt( ident_t* id_ref, int gtid, double *lhs, double rhs, int flag);
void __kmpc_atomic_float8_sub( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_sub_rev( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_swp( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float8_wr( ident_t* id_ref, int gtid, double *lhs, double rhs);
void __kmpc_atomic_float10_add( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
long double __kmpc_atomic_float10_add_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
void __kmpc_atomic_float10_add( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_div( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
long double __kmpc_atomic_float10_div_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
long double __kmpc_atomic_float10_div_rev_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
void __kmpc_atomic_float10_div( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_div_rev( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_mul( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
long double __kmpc_atomic_float10_mul_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
void __kmpc_atomic_float10_mul( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_rd( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_sub( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
long double __kmpc_atomic_float10_sub_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
long double __kmpc_atomic_float10_sub_rev_cpt( ident_t* id_ref, int gtid, long double *lhs, long double rhs, int flag);
void __kmpc_atomic_float10_sub( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_sub_rev( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_swp( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float10_wr( ident_t* id_ref, int gtid, long double *lhs, long double rhs);
void __kmpc_atomic_float16_add( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_add_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_div( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_div_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
__float128 __kmpc_atomic_float16_div_rev_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_div_rev( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
void __kmpc_atomic_float16_max( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_max_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_min( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_min_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_mul( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_mul_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_rd( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
void __kmpc_atomic_float16_sub( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
__float128 __kmpc_atomic_float16_sub_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
__float128 __kmpc_atomic_float16_sub_rev_cpt( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs, int flag);
void __kmpc_atomic_float16_sub_rev( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
void __kmpc_atomic_float16_swp( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
void __kmpc_atomic_float16_wr( ident_t* id_ref, int gtid, __float128 *lhs, __float128 rhs);
void __kmpc_atomic_cmplx4_add( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_add( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_add_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_div( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_div( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_div_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_div_rev_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_div_rev( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_mul( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_mul( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_mul_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_rd( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_sub( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_sub( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_sub_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_sub_rev_cpt( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs, _Complex float out, int flag);
void __kmpc_atomic_cmplx4_sub_rev( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_swp( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx4_wr( ident_t* id_ref, int gtid, _Complex float *lhs, _Complex float rhs);
void __kmpc_atomic_cmplx8_add( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_add_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_div( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_div_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_div_rev_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_div_rev( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_mul( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_mul_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_rd( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_sub( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_sub_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_sub_rev_cpt( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs, _Complex double out, int flag);
void __kmpc_atomic_cmplx8_sub_rev( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_swp( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx8_wr( ident_t* id_ref, int gtid, _Complex double *lhs, _Complex double rhs);
void __kmpc_atomic_cmplx10_add( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_add_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_div( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_div_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_div_rev_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_div_rev( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_mul( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_mul_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_rd( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_sub( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_sub_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_sub_rev_cpt( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs, _Complex long double out, int flag);
void __kmpc_atomic_cmplx10_sub_rev( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_swp( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
void __kmpc_atomic_cmplx10_wr( ident_t* id_ref, int gtid, _Complex long double *lhs, _Complex long double rhs);
