PROGRAM MAIN
    USE, INTRINSIC :: ISO_FORTRAN_ENV
    IMPLICIT NONE

    PRINT "(A)", "MODULE ISO_FORTRAN_ENV, INTRINSIC"
    PRINT "(A)", ""
    PRINT "('INTEGER :: ',A,' = ',I0)", "CHARACTER_STORAGE_SIZE", CHARACTER_STORAGE_SIZE
    PRINT "('INTEGER :: ',A,' = ',I0)", "ERROR_UNIT"            , ERROR_UNIT
    PRINT "('INTEGER :: ',A,' = ',I0)", "FILE_STORAGE_SIZE"     , FILE_STORAGE_SIZE
    PRINT "('INTEGER :: ',A,' = ',I0)", "INPUT_UNIT"            , INPUT_UNIT
    PRINT "('INTEGER :: ',A,' = ',I0)", "IOSTAT_END"            , IOSTAT_END
    PRINT "('INTEGER :: ',A,' = ',I0)", "IOSTAT_EOR"            , IOSTAT_EOR
    PRINT "('INTEGER :: ',A,' = ',I0)", "NUMERIC_STORAGE_SIZE"  , NUMERIC_STORAGE_SIZE
    PRINT "('INTEGER :: ',A,' = ',I0)", "OUTPUT_UNIT"           , OUTPUT_UNIT
    PRINT "(A)", ""
    PRINT "(A)", "END MODULE ISO_FORTRAN_ENV"
END PROGRAM MAIN
