MODULE ISO_FORTRAN_ENV, INTRINSIC
  INTEGER :: CHARACTER_STORAGE_SIZE
  INTEGER :: ERROR_UNIT
  INTEGER :: FILE_STORAGE_SIZE
  INTEGER :: INPUT_UNIT
  INTEGER :: IOSTAT_END
  INTEGER :: IOSTAT_EOR
  INTEGER :: NUMERIC_STORAGE_SIZE
  INTEGER :: OUTPUT_UNIT
END MODULE ISO_FORTRAN_ENV

