include $(top_srcdir)/src/tl/Makefile.tl

phasesdir = $(pkglibdir)

phases_cflags= $(tl_cflags)

phases_cxxflags=$(tl_cflags)

phases_libadd=$(tl_libadd) 

phases_ldflags=-avoid-version $(tl_no_undefined)
if WINDOWS_BUILD
else
phases_ldflags += \
    -Wl,@RPATH_PARAMETER@,\$$ORIGIN \
    -Wl,@RPATH_PARAMETER@,\$$ORIGIN/.. \
	-Wl,-z,origin \
	--enable-new-dtags \
	$(END)
endif
