#include "tl-nanox-nodecl.hpp"
#include "tl-source.hpp"
#include "tl-nodecl.hpp"
#include "cxx-utils.h"

namespace TL { namespace Nanox {

void Lowering::pre_run(DTO& dto)
{
    std::cerr << "Nanos++ prerun" << std::endl;

    if (!IS_FORTRAN_LANGUAGE)
        return;

    Nodecl::NodeclBase top_level = dto["nodecl"];

    TL::Source src;


    src <<

"# 1 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"# 1 \"<built-in>\"\n"
"# 1 \"<command-line>\"\n"
"# 1 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"# 23 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"# 1 \"/usr/include/unistd.h\" 1 3 4\n"
"# 26 \"/usr/include/unistd.h\" 3 4\n"
"# 1 \"/usr/include/features.h\" 1 3 4\n"
"# 323 \"/usr/include/features.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/predefs.h\" 1 3 4\n"
"# 324 \"/usr/include/features.h\" 2 3 4\n"
"# 356 \"/usr/include/features.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/sys/cdefs.h\" 1 3 4\n"
"# 353 \"/usr/include/x86_64-linux-gnu/sys/cdefs.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wordsize.h\" 1 3 4\n"
"# 354 \"/usr/include/x86_64-linux-gnu/sys/cdefs.h\" 2 3 4\n"
"# 357 \"/usr/include/features.h\" 2 3 4\n"
"# 388 \"/usr/include/features.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/gnu/stubs.h\" 1 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wordsize.h\" 1 3 4\n"
"# 5 \"/usr/include/x86_64-linux-gnu/gnu/stubs.h\" 2 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/gnu/stubs-64.h\" 1 3 4\n"
"# 10 \"/usr/include/x86_64-linux-gnu/gnu/stubs.h\" 2 3 4\n"
"# 389 \"/usr/include/features.h\" 2 3 4\n"
"# 27 \"/usr/include/unistd.h\" 2 3 4\n"
"# 203 \"/usr/include/unistd.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/posix_opt.h\" 1 3 4\n"
"# 204 \"/usr/include/unistd.h\" 2 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/environments.h\" 1 3 4\n"
"# 23 \"/usr/include/x86_64-linux-gnu/bits/environments.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wordsize.h\" 1 3 4\n"
"# 24 \"/usr/include/x86_64-linux-gnu/bits/environments.h\" 2 3 4\n"
"# 208 \"/usr/include/unistd.h\" 2 3 4\n"
"# 218 \"/usr/include/unistd.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/types.h\" 1 3 4\n"
"# 28 \"/usr/include/x86_64-linux-gnu/bits/types.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wordsize.h\" 1 3 4\n"
"# 29 \"/usr/include/x86_64-linux-gnu/bits/types.h\" 2 3 4\n"
"typedef unsigned char __u_char;\n"
"typedef unsigned short int __u_short;\n"
"typedef unsigned int __u_int;\n"
"typedef unsigned long int __u_long;\n"
"typedef signed char __int8_t;\n"
"typedef unsigned char __uint8_t;\n"
"typedef signed short int __int16_t;\n"
"typedef unsigned short int __uint16_t;\n"
"typedef signed int __int32_t;\n"
"typedef unsigned int __uint32_t;\n"
"typedef signed long int __int64_t;\n"
"typedef unsigned long int __uint64_t;\n"
"typedef long int __quad_t;\n"
"typedef unsigned long int __u_quad_t;\n"
"# 131 \"/usr/include/x86_64-linux-gnu/bits/types.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/typesizes.h\" 1 3 4\n"
"# 132 \"/usr/include/x86_64-linux-gnu/bits/types.h\" 2 3 4\n"
"typedef unsigned long int __dev_t;\n"
"typedef unsigned int __uid_t;\n"
"typedef unsigned int __gid_t;\n"
"typedef unsigned long int __ino_t;\n"
"typedef unsigned long int __ino64_t;\n"
"typedef unsigned int __mode_t;\n"
"typedef unsigned long int __nlink_t;\n"
"typedef long int __off_t;\n"
"typedef long int __off64_t;\n"
"typedef int __pid_t;\n"
"typedef struct { int __val[2]; } __fsid_t;\n"
"typedef long int __clock_t;\n"
"typedef unsigned long int __rlim_t;\n"
"typedef unsigned long int __rlim64_t;\n"
"typedef unsigned int __id_t;\n"
"typedef long int __time_t;\n"
"typedef unsigned int __useconds_t;\n"
"typedef long int __suseconds_t;\n"
"typedef int __daddr_t;\n"
"typedef long int __swblk_t;\n"
"typedef int __key_t;\n"
"typedef int __clockid_t;\n"
"typedef void * __timer_t;\n"
"typedef long int __blksize_t;\n"
"typedef long int __blkcnt_t;\n"
"typedef long int __blkcnt64_t;\n"
"typedef unsigned long int __fsblkcnt_t;\n"
"typedef unsigned long int __fsblkcnt64_t;\n"
"typedef unsigned long int __fsfilcnt_t;\n"
"typedef unsigned long int __fsfilcnt64_t;\n"
"typedef long int __ssize_t;\n"
"typedef __off64_t __loff_t;\n"
"typedef __quad_t *__qaddr_t;\n"
"typedef char *__caddr_t;\n"
"typedef long int __intptr_t;\n"
"typedef unsigned int __socklen_t;\n"
"# 219 \"/usr/include/unistd.h\" 2 3 4\n"
"typedef __ssize_t ssize_t;\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 1 3 4\n"
"# 212 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 3 4\n"
"typedef long unsigned int size_t;\n"
"# 228 \"/usr/include/unistd.h\" 2 3 4\n"
"typedef __gid_t gid_t;\n"
"typedef __uid_t uid_t;\n"
"typedef __off_t off_t;\n"
"# 256 \"/usr/include/unistd.h\" 3 4\n"
"typedef __useconds_t useconds_t;\n"
"typedef __pid_t pid_t;\n"
"typedef __intptr_t intptr_t;\n"
"typedef __socklen_t socklen_t;\n"
"# 288 \"/usr/include/unistd.h\" 3 4\n"
"extern int access (__const char *__name, int __type) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"# 305 \"/usr/include/unistd.h\" 3 4\n"
"extern int faccessat (int __fd, __const char *__file, int __type, int __flag)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2))) ;\n"
"# 331 \"/usr/include/unistd.h\" 3 4\n"
"extern __off_t lseek (int __fd, __off_t __offset, int __whence) __attribute__ ((__nothrow__));\n"
"# 350 \"/usr/include/unistd.h\" 3 4\n"
"extern int close (int __fd);\n"
"extern ssize_t read (int __fd, void *__buf, size_t __nbytes) ;\n"
"extern ssize_t write (int __fd, __const void *__buf, size_t __n) ;\n"
"# 373 \"/usr/include/unistd.h\" 3 4\n"
"extern ssize_t pread (int __fd, void *__buf, size_t __nbytes,\n"
"        __off_t __offset) ;\n"
"extern ssize_t pwrite (int __fd, __const void *__buf, size_t __n,\n"
"         __off_t __offset) ;\n"
"# 414 \"/usr/include/unistd.h\" 3 4\n"
"extern int pipe (int __pipedes[2]) __attribute__ ((__nothrow__)) ;\n"
"# 429 \"/usr/include/unistd.h\" 3 4\n"
"extern unsigned int alarm (unsigned int __seconds) __attribute__ ((__nothrow__));\n"
"# 441 \"/usr/include/unistd.h\" 3 4\n"
"extern unsigned int sleep (unsigned int __seconds);\n"
"extern __useconds_t ualarm (__useconds_t __value, __useconds_t __interval)\n"
"     __attribute__ ((__nothrow__));\n"
"extern int usleep (__useconds_t __useconds);\n"
"# 466 \"/usr/include/unistd.h\" 3 4\n"
"extern int pause (void);\n"
"extern int chown (__const char *__file, __uid_t __owner, __gid_t __group)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int fchown (int __fd, __uid_t __owner, __gid_t __group) __attribute__ ((__nothrow__)) ;\n"
"extern int lchown (__const char *__file, __uid_t __owner, __gid_t __group)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int fchownat (int __fd, __const char *__file, __uid_t __owner,\n"
"       __gid_t __group, int __flag)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2))) ;\n"
"extern int chdir (__const char *__path) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int fchdir (int __fd) __attribute__ ((__nothrow__)) ;\n"
"# 508 \"/usr/include/unistd.h\" 3 4\n"
"extern char *getcwd (char *__buf, size_t __size) __attribute__ ((__nothrow__)) ;\n"
"# 522 \"/usr/include/unistd.h\" 3 4\n"
"extern char *getwd (char *__buf)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) __attribute__ ((__deprecated__)) ;\n"
"extern int dup (int __fd) __attribute__ ((__nothrow__)) ;\n"
"extern int dup2 (int __fd, int __fd2) __attribute__ ((__nothrow__));\n"
"# 540 \"/usr/include/unistd.h\" 3 4\n"
"extern char **__environ;\n"
"extern int execve (__const char *__path, char *__const __argv[],\n"
"     char *__const __envp[]) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"extern int fexecve (int __fd, char *__const __argv[], char *__const __envp[])\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2)));\n"
"extern int execv (__const char *__path, char *__const __argv[])\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"extern int execle (__const char *__path, __const char *__arg, ...)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"extern int execl (__const char *__path, __const char *__arg, ...)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"extern int execvp (__const char *__file, char *__const __argv[])\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"extern int execlp (__const char *__file, __const char *__arg, ...)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2)));\n"
"# 595 \"/usr/include/unistd.h\" 3 4\n"
"extern int nice (int __inc) __attribute__ ((__nothrow__)) ;\n"
"extern void _exit (int __status) __attribute__ ((__noreturn__));\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/confname.h\" 1 3 4\n"
"# 26 \"/usr/include/x86_64-linux-gnu/bits/confname.h\" 3 4\n"
"enum\n"
"  {\n"
"    _PC_LINK_MAX,\n"
"    _PC_MAX_CANON,\n"
"    _PC_MAX_INPUT,\n"
"    _PC_NAME_MAX,\n"
"    _PC_PATH_MAX,\n"
"    _PC_PIPE_BUF,\n"
"    _PC_CHOWN_RESTRICTED,\n"
"    _PC_NO_TRUNC,\n"
"    _PC_VDISABLE,\n"
"    _PC_SYNC_IO,\n"
"    _PC_ASYNC_IO,\n"
"    _PC_PRIO_IO,\n"
"    _PC_SOCK_MAXBUF,\n"
"    _PC_FILESIZEBITS,\n"
"    _PC_REC_INCR_XFER_SIZE,\n"
"    _PC_REC_MAX_XFER_SIZE,\n"
"    _PC_REC_MIN_XFER_SIZE,\n"
"    _PC_REC_XFER_ALIGN,\n"
"    _PC_ALLOC_SIZE_MIN,\n"
"    _PC_SYMLINK_MAX,\n"
"    _PC_2_SYMLINKS\n"
"  };\n"
"enum\n"
"  {\n"
"    _SC_ARG_MAX,\n"
"    _SC_CHILD_MAX,\n"
"    _SC_CLK_TCK,\n"
"    _SC_NGROUPS_MAX,\n"
"    _SC_OPEN_MAX,\n"
"    _SC_STREAM_MAX,\n"
"    _SC_TZNAME_MAX,\n"
"    _SC_JOB_CONTROL,\n"
"    _SC_SAVED_IDS,\n"
"    _SC_REALTIME_SIGNALS,\n"
"    _SC_PRIORITY_SCHEDULING,\n"
"    _SC_TIMERS,\n"
"    _SC_ASYNCHRONOUS_IO,\n"
"    _SC_PRIORITIZED_IO,\n"
"    _SC_SYNCHRONIZED_IO,\n"
"    _SC_FSYNC,\n"
"    _SC_MAPPED_FILES,\n"
"    _SC_MEMLOCK,\n"
"    _SC_MEMLOCK_RANGE,\n"
"    _SC_MEMORY_PROTECTION,\n"
"    _SC_MESSAGE_PASSING,\n"
"    _SC_SEMAPHORES,\n"
"    _SC_SHARED_MEMORY_OBJECTS,\n"
"    _SC_AIO_LISTIO_MAX,\n"
"    _SC_AIO_MAX,\n"
"    _SC_AIO_PRIO_DELTA_MAX,\n"
"    _SC_DELAYTIMER_MAX,\n"
"    _SC_MQ_OPEN_MAX,\n"
"    _SC_MQ_PRIO_MAX,\n"
"    _SC_VERSION,\n"
"    _SC_PAGESIZE,\n"
"    _SC_RTSIG_MAX,\n"
"    _SC_SEM_NSEMS_MAX,\n"
"    _SC_SEM_VALUE_MAX,\n"
"    _SC_SIGQUEUE_MAX,\n"
"    _SC_TIMER_MAX,\n"
"    _SC_BC_BASE_MAX,\n"
"    _SC_BC_DIM_MAX,\n"
"    _SC_BC_SCALE_MAX,\n"
"    _SC_BC_STRING_MAX,\n"
"    _SC_COLL_WEIGHTS_MAX,\n"
"    _SC_EQUIV_CLASS_MAX,\n"
"    _SC_EXPR_NEST_MAX,\n"
"    _SC_LINE_MAX,\n"
"    _SC_RE_DUP_MAX,\n"
"    _SC_CHARCLASS_NAME_MAX,\n"
"    _SC_2_VERSION,\n"
"    _SC_2_C_BIND,\n"
"    _SC_2_C_DEV,\n"
"    _SC_2_FORT_DEV,\n"
"    _SC_2_FORT_RUN,\n"
"    _SC_2_SW_DEV,\n"
"    _SC_2_LOCALEDEF,\n"
"    _SC_PII,\n"
"    _SC_PII_XTI,\n"
"    _SC_PII_SOCKET,\n"
"    _SC_PII_INTERNET,\n"
"    _SC_PII_OSI,\n"
"    _SC_POLL,\n"
"    _SC_SELECT,\n"
"    _SC_UIO_MAXIOV,\n"
"    _SC_IOV_MAX = _SC_UIO_MAXIOV,\n"
"    _SC_PII_INTERNET_STREAM,\n"
"    _SC_PII_INTERNET_DGRAM,\n"
"    _SC_PII_OSI_COTS,\n"
"    _SC_PII_OSI_CLTS,\n"
"    _SC_PII_OSI_M,\n"
"    _SC_T_IOV_MAX,\n"
"    _SC_THREADS,\n"
"    _SC_THREAD_SAFE_FUNCTIONS,\n"
"    _SC_GETGR_R_SIZE_MAX,\n"
"    _SC_GETPW_R_SIZE_MAX,\n"
"    _SC_LOGIN_NAME_MAX,\n"
"    _SC_TTY_NAME_MAX,\n"
"    _SC_THREAD_DESTRUCTOR_ITERATIONS,\n"
"    _SC_THREAD_KEYS_MAX,\n"
"    _SC_THREAD_STACK_MIN,\n"
"    _SC_THREAD_THREADS_MAX,\n"
"    _SC_THREAD_ATTR_STACKADDR,\n"
"    _SC_THREAD_ATTR_STACKSIZE,\n"
"    _SC_THREAD_PRIORITY_SCHEDULING,\n"
"    _SC_THREAD_PRIO_INHERIT,\n"
"    _SC_THREAD_PRIO_PROTECT,\n"
"    _SC_THREAD_PROCESS_SHARED,\n"
"    _SC_NPROCESSORS_CONF,\n"
"    _SC_NPROCESSORS_ONLN,\n"
"    _SC_PHYS_PAGES,\n"
"    _SC_AVPHYS_PAGES,\n"
"    _SC_ATEXIT_MAX,\n"
"    _SC_PASS_MAX,\n"
"    _SC_XOPEN_VERSION,\n"
"    _SC_XOPEN_XCU_VERSION,\n"
"    _SC_XOPEN_UNIX,\n"
"    _SC_XOPEN_CRYPT,\n"
"    _SC_XOPEN_ENH_I18N,\n"
"    _SC_XOPEN_SHM,\n"
"    _SC_2_CHAR_TERM,\n"
"    _SC_2_C_VERSION,\n"
"    _SC_2_UPE,\n"
"    _SC_XOPEN_XPG2,\n"
"    _SC_XOPEN_XPG3,\n"
"    _SC_XOPEN_XPG4,\n"
"    _SC_CHAR_BIT,\n"
"    _SC_CHAR_MAX,\n"
"    _SC_CHAR_MIN,\n"
"    _SC_INT_MAX,\n"
"    _SC_INT_MIN,\n"
"    _SC_LONG_BIT,\n"
"    _SC_WORD_BIT,\n"
"    _SC_MB_LEN_MAX,\n"
"    _SC_NZERO,\n"
"    _SC_SSIZE_MAX,\n"
"    _SC_SCHAR_MAX,\n"
"    _SC_SCHAR_MIN,\n"
"    _SC_SHRT_MAX,\n"
"    _SC_SHRT_MIN,\n"
"    _SC_UCHAR_MAX,\n"
"    _SC_UINT_MAX,\n"
"    _SC_ULONG_MAX,\n"
"    _SC_USHRT_MAX,\n"
"    _SC_NL_ARGMAX,\n"
"    _SC_NL_LANGMAX,\n"
"    _SC_NL_MSGMAX,\n"
"    _SC_NL_NMAX,\n"
"    _SC_NL_SETMAX,\n"
"    _SC_NL_TEXTMAX,\n"
"    _SC_XBS5_ILP32_OFF32,\n"
"    _SC_XBS5_ILP32_OFFBIG,\n"
"    _SC_XBS5_LP64_OFF64,\n"
"    _SC_XBS5_LPBIG_OFFBIG,\n"
"    _SC_XOPEN_LEGACY,\n"
"    _SC_XOPEN_REALTIME,\n"
"    _SC_XOPEN_REALTIME_THREADS,\n"
"    _SC_ADVISORY_INFO,\n"
"    _SC_BARRIERS,\n"
"    _SC_BASE,\n"
"    _SC_C_LANG_SUPPORT,\n"
"    _SC_C_LANG_SUPPORT_R,\n"
"    _SC_CLOCK_SELECTION,\n"
"    _SC_CPUTIME,\n"
"    _SC_THREAD_CPUTIME,\n"
"    _SC_DEVICE_IO,\n"
"    _SC_DEVICE_SPECIFIC,\n"
"    _SC_DEVICE_SPECIFIC_R,\n"
"    _SC_FD_MGMT,\n"
"    _SC_FIFO,\n"
"    _SC_PIPE,\n"
"    _SC_FILE_ATTRIBUTES,\n"
"    _SC_FILE_LOCKING,\n"
"    _SC_FILE_SYSTEM,\n"
"    _SC_MONOTONIC_CLOCK,\n"
"    _SC_MULTI_PROCESS,\n"
"    _SC_SINGLE_PROCESS,\n"
"    _SC_NETWORKING,\n"
"    _SC_READER_WRITER_LOCKS,\n"
"    _SC_SPIN_LOCKS,\n"
"    _SC_REGEXP,\n"
"    _SC_REGEX_VERSION,\n"
"    _SC_SHELL,\n"
"    _SC_SIGNALS,\n"
"    _SC_SPAWN,\n"
"    _SC_SPORADIC_SERVER,\n"
"    _SC_THREAD_SPORADIC_SERVER,\n"
"    _SC_SYSTEM_DATABASE,\n"
"    _SC_SYSTEM_DATABASE_R,\n"
"    _SC_TIMEOUTS,\n"
"    _SC_TYPED_MEMORY_OBJECTS,\n"
"    _SC_USER_GROUPS,\n"
"    _SC_USER_GROUPS_R,\n"
"    _SC_2_PBS,\n"
"    _SC_2_PBS_ACCOUNTING,\n"
"    _SC_2_PBS_LOCATE,\n"
"    _SC_2_PBS_MESSAGE,\n"
"    _SC_2_PBS_TRACK,\n"
"    _SC_SYMLOOP_MAX,\n"
"    _SC_STREAMS,\n"
"    _SC_2_PBS_CHECKPOINT,\n"
"    _SC_V6_ILP32_OFF32,\n"
"    _SC_V6_ILP32_OFFBIG,\n"
"    _SC_V6_LP64_OFF64,\n"
"    _SC_V6_LPBIG_OFFBIG,\n"
"    _SC_HOST_NAME_MAX,\n"
"    _SC_TRACE,\n"
"    _SC_TRACE_EVENT_FILTER,\n"
"    _SC_TRACE_INHERIT,\n"
"    _SC_TRACE_LOG,\n"
"    _SC_LEVEL1_ICACHE_SIZE,\n"
"    _SC_LEVEL1_ICACHE_ASSOC,\n"
"    _SC_LEVEL1_ICACHE_LINESIZE,\n"
"    _SC_LEVEL1_DCACHE_SIZE,\n"
"    _SC_LEVEL1_DCACHE_ASSOC,\n"
"    _SC_LEVEL1_DCACHE_LINESIZE,\n"
"    _SC_LEVEL2_CACHE_SIZE,\n"
"    _SC_LEVEL2_CACHE_ASSOC,\n"
"    _SC_LEVEL2_CACHE_LINESIZE,\n"
"    _SC_LEVEL3_CACHE_SIZE,\n"
"    _SC_LEVEL3_CACHE_ASSOC,\n"
"    _SC_LEVEL3_CACHE_LINESIZE,\n"
"    _SC_LEVEL4_CACHE_SIZE,\n"
"    _SC_LEVEL4_CACHE_ASSOC,\n"
"    _SC_LEVEL4_CACHE_LINESIZE,\n"
"    _SC_IPV6 = _SC_LEVEL1_ICACHE_SIZE + 50,\n"
"    _SC_RAW_SOCKETS,\n"
"    _SC_V7_ILP32_OFF32,\n"
"    _SC_V7_ILP32_OFFBIG,\n"
"    _SC_V7_LP64_OFF64,\n"
"    _SC_V7_LPBIG_OFFBIG,\n"
"    _SC_SS_REPL_MAX,\n"
"    _SC_TRACE_EVENT_NAME_MAX,\n"
"    _SC_TRACE_NAME_MAX,\n"
"    _SC_TRACE_SYS_MAX,\n"
"    _SC_TRACE_USER_EVENT_MAX,\n"
"    _SC_XOPEN_STREAMS,\n"
"    _SC_THREAD_ROBUST_PRIO_INHERIT,\n"
"    _SC_THREAD_ROBUST_PRIO_PROTECT\n"
"  };\n"
"enum\n"
"  {\n"
"    _CS_PATH,\n"
"    _CS_V6_WIDTH_RESTRICTED_ENVS,\n"
"    _CS_GNU_LIBC_VERSION,\n"
"    _CS_GNU_LIBPTHREAD_VERSION,\n"
"    _CS_V5_WIDTH_RESTRICTED_ENVS,\n"
"    _CS_V7_WIDTH_RESTRICTED_ENVS,\n"
"    _CS_LFS_CFLAGS = 1000,\n"
"    _CS_LFS_LDFLAGS,\n"
"    _CS_LFS_LIBS,\n"
"    _CS_LFS_LINTFLAGS,\n"
"    _CS_LFS64_CFLAGS,\n"
"    _CS_LFS64_LDFLAGS,\n"
"    _CS_LFS64_LIBS,\n"
"    _CS_LFS64_LINTFLAGS,\n"
"    _CS_XBS5_ILP32_OFF32_CFLAGS = 1100,\n"
"    _CS_XBS5_ILP32_OFF32_LDFLAGS,\n"
"    _CS_XBS5_ILP32_OFF32_LIBS,\n"
"    _CS_XBS5_ILP32_OFF32_LINTFLAGS,\n"
"    _CS_XBS5_ILP32_OFFBIG_CFLAGS,\n"
"    _CS_XBS5_ILP32_OFFBIG_LDFLAGS,\n"
"    _CS_XBS5_ILP32_OFFBIG_LIBS,\n"
"    _CS_XBS5_ILP32_OFFBIG_LINTFLAGS,\n"
"    _CS_XBS5_LP64_OFF64_CFLAGS,\n"
"    _CS_XBS5_LP64_OFF64_LDFLAGS,\n"
"    _CS_XBS5_LP64_OFF64_LIBS,\n"
"    _CS_XBS5_LP64_OFF64_LINTFLAGS,\n"
"    _CS_XBS5_LPBIG_OFFBIG_CFLAGS,\n"
"    _CS_XBS5_LPBIG_OFFBIG_LDFLAGS,\n"
"    _CS_XBS5_LPBIG_OFFBIG_LIBS,\n"
"    _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFF32_CFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFF32_LDFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFF32_LIBS,\n"
"    _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS,\n"
"    _CS_POSIX_V6_ILP32_OFFBIG_LIBS,\n"
"    _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS,\n"
"    _CS_POSIX_V6_LP64_OFF64_CFLAGS,\n"
"    _CS_POSIX_V6_LP64_OFF64_LDFLAGS,\n"
"    _CS_POSIX_V6_LP64_OFF64_LIBS,\n"
"    _CS_POSIX_V6_LP64_OFF64_LINTFLAGS,\n"
"    _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS,\n"
"    _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS,\n"
"    _CS_POSIX_V6_LPBIG_OFFBIG_LIBS,\n"
"    _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFF32_CFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFF32_LDFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFF32_LIBS,\n"
"    _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS,\n"
"    _CS_POSIX_V7_ILP32_OFFBIG_LIBS,\n"
"    _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS,\n"
"    _CS_POSIX_V7_LP64_OFF64_CFLAGS,\n"
"    _CS_POSIX_V7_LP64_OFF64_LDFLAGS,\n"
"    _CS_POSIX_V7_LP64_OFF64_LIBS,\n"
"    _CS_POSIX_V7_LP64_OFF64_LINTFLAGS,\n"
"    _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS,\n"
"    _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS,\n"
"    _CS_POSIX_V7_LPBIG_OFFBIG_LIBS,\n"
"    _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS,\n"
"    _CS_V6_ENV,\n"
"    _CS_V7_ENV\n"
"  };\n"
"# 607 \"/usr/include/unistd.h\" 2 3 4\n"
"extern long int pathconf (__const char *__path, int __name)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"extern long int fpathconf (int __fd, int __name) __attribute__ ((__nothrow__));\n"
"extern long int sysconf (int __name) __attribute__ ((__nothrow__));\n"
"extern size_t confstr (int __name, char *__buf, size_t __len) __attribute__ ((__nothrow__));\n"
"extern __pid_t getpid (void) __attribute__ ((__nothrow__));\n"
"extern __pid_t getppid (void) __attribute__ ((__nothrow__));\n"
"extern __pid_t getpgrp (void) __attribute__ ((__nothrow__));\n"
"# 643 \"/usr/include/unistd.h\" 3 4\n"
"extern __pid_t __getpgid (__pid_t __pid) __attribute__ ((__nothrow__));\n"
"extern __pid_t getpgid (__pid_t __pid) __attribute__ ((__nothrow__));\n"
"extern int setpgid (__pid_t __pid, __pid_t __pgid) __attribute__ ((__nothrow__));\n"
"# 669 \"/usr/include/unistd.h\" 3 4\n"
"extern int setpgrp (void) __attribute__ ((__nothrow__));\n"
"# 686 \"/usr/include/unistd.h\" 3 4\n"
"extern __pid_t setsid (void) __attribute__ ((__nothrow__));\n"
"extern __pid_t getsid (__pid_t __pid) __attribute__ ((__nothrow__));\n"
"extern __uid_t getuid (void) __attribute__ ((__nothrow__));\n"
"extern __uid_t geteuid (void) __attribute__ ((__nothrow__));\n"
"extern __gid_t getgid (void) __attribute__ ((__nothrow__));\n"
"extern __gid_t getegid (void) __attribute__ ((__nothrow__));\n"
"extern int getgroups (int __size, __gid_t __list[]) __attribute__ ((__nothrow__)) ;\n"
"# 719 \"/usr/include/unistd.h\" 3 4\n"
"extern int setuid (__uid_t __uid) __attribute__ ((__nothrow__));\n"
"extern int setreuid (__uid_t __ruid, __uid_t __euid) __attribute__ ((__nothrow__));\n"
"extern int seteuid (__uid_t __uid) __attribute__ ((__nothrow__));\n"
"extern int setgid (__gid_t __gid) __attribute__ ((__nothrow__));\n"
"extern int setregid (__gid_t __rgid, __gid_t __egid) __attribute__ ((__nothrow__));\n"
"extern int setegid (__gid_t __gid) __attribute__ ((__nothrow__));\n"
"# 775 \"/usr/include/unistd.h\" 3 4\n"
"extern __pid_t fork (void) __attribute__ ((__nothrow__));\n"
"extern __pid_t vfork (void) __attribute__ ((__nothrow__));\n"
"extern char *ttyname (int __fd) __attribute__ ((__nothrow__));\n"
"extern int ttyname_r (int __fd, char *__buf, size_t __buflen)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2))) ;\n"
"extern int isatty (int __fd) __attribute__ ((__nothrow__));\n"
"extern int ttyslot (void) __attribute__ ((__nothrow__));\n"
"extern int link (__const char *__from, __const char *__to)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2))) ;\n"
"extern int linkat (int __fromfd, __const char *__from, int __tofd,\n"
"     __const char *__to, int __flags)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2, 4))) ;\n"
"extern int symlink (__const char *__from, __const char *__to)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2))) ;\n"
"extern ssize_t readlink (__const char *__restrict __path,\n"
"    char *__restrict __buf, size_t __len)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 2))) ;\n"
"extern int symlinkat (__const char *__from, int __tofd,\n"
"        __const char *__to) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1, 3))) ;\n"
"extern ssize_t readlinkat (int __fd, __const char *__restrict __path,\n"
"      char *__restrict __buf, size_t __len)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2, 3))) ;\n"
"extern int unlink (__const char *__name) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"extern int unlinkat (int __fd, __const char *__name, int __flag)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (2)));\n"
"extern int rmdir (__const char *__path) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"extern __pid_t tcgetpgrp (int __fd) __attribute__ ((__nothrow__));\n"
"extern int tcsetpgrp (int __fd, __pid_t __pgrp_id) __attribute__ ((__nothrow__));\n"
"extern char *getlogin (void);\n"
"extern int getlogin_r (char *__name, size_t __name_len) __attribute__ ((__nonnull__ (1)));\n"
"extern int setlogin (__const char *__name) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"# 890 \"/usr/include/unistd.h\" 3 4\n"
"# 1 \"/usr/include/getopt.h\" 1 3 4\n"
"# 59 \"/usr/include/getopt.h\" 3 4\n"
"extern char *optarg;\n"
"# 73 \"/usr/include/getopt.h\" 3 4\n"
"extern int optind;\n"
"extern int opterr;\n"
"extern int optopt;\n"
"# 152 \"/usr/include/getopt.h\" 3 4\n"
"extern int getopt (int ___argc, char *const *___argv, const char *__shortopts)\n"
"       __attribute__ ((__nothrow__));\n"
"# 891 \"/usr/include/unistd.h\" 2 3 4\n"
"extern int gethostname (char *__name, size_t __len) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"extern int sethostname (__const char *__name, size_t __len)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int sethostid (long int __id) __attribute__ ((__nothrow__)) ;\n"
"extern int getdomainname (char *__name, size_t __len)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int setdomainname (__const char *__name, size_t __len)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int vhangup (void) __attribute__ ((__nothrow__));\n"
"extern int revoke (__const char *__file) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern int profil (unsigned short int *__sample_buffer, size_t __size,\n"
"     size_t __offset, unsigned int __scale)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1)));\n"
"extern int acct (__const char *__name) __attribute__ ((__nothrow__));\n"
"extern char *getusershell (void) __attribute__ ((__nothrow__));\n"
"extern void endusershell (void) __attribute__ ((__nothrow__));\n"
"extern void setusershell (void) __attribute__ ((__nothrow__));\n"
"extern int daemon (int __nochdir, int __noclose) __attribute__ ((__nothrow__)) ;\n"
"extern int chroot (__const char *__path) __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"extern char *getpass (__const char *__prompt) __attribute__ ((__nonnull__ (1)));\n"
"# 976 \"/usr/include/unistd.h\" 3 4\n"
"extern int fsync (int __fd);\n"
"extern long int gethostid (void);\n"
"extern void sync (void) __attribute__ ((__nothrow__));\n"
"extern int getpagesize (void) __attribute__ ((__nothrow__)) __attribute__ ((__const__));\n"
"extern int getdtablesize (void) __attribute__ ((__nothrow__));\n"
"# 1007 \"/usr/include/unistd.h\" 3 4\n"
"extern int truncate (__const char *__file, __off_t __length)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__nonnull__ (1))) ;\n"
"# 1029 \"/usr/include/unistd.h\" 3 4\n"
"extern int ftruncate (int __fd, __off_t __length) __attribute__ ((__nothrow__)) ;\n"
"# 1050 \"/usr/include/unistd.h\" 3 4\n"
"extern int brk (void *__addr) __attribute__ ((__nothrow__)) ;\n"
"extern void *sbrk (intptr_t __delta) __attribute__ ((__nothrow__));\n"
"# 1071 \"/usr/include/unistd.h\" 3 4\n"
"extern long int syscall (long int __sysno, ...) __attribute__ ((__nothrow__));\n"
"# 1094 \"/usr/include/unistd.h\" 3 4\n"
"extern int lockf (int __fd, int __cmd, __off_t __len) ;\n"
"# 1125 \"/usr/include/unistd.h\" 3 4\n"
"extern int fdatasync (int __fildes);\n"
"# 1154 \"/usr/include/unistd.h\" 3 4\n"
"extern char *ctermid (char *__s) __attribute__ ((__nothrow__));\n"
"# 1163 \"/usr/include/unistd.h\" 3 4\n"
"# 24 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\" 2\n"
"# 1 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\" 1\n"
"# 23 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\"\n"
"# 1 \"/usr/include/stdio.h\" 1 3 4\n"
"# 30 \"/usr/include/stdio.h\" 3 4\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 1 3 4\n"
"# 35 \"/usr/include/stdio.h\" 2 3 4\n"
"# 45 \"/usr/include/stdio.h\" 3 4\n"
"struct _IO_FILE;\n"
"typedef struct _IO_FILE FILE;\n"
"# 65 \"/usr/include/stdio.h\" 3 4\n"
"typedef struct _IO_FILE __FILE;\n"
"# 75 \"/usr/include/stdio.h\" 3 4\n"
"# 1 \"/usr/include/libio.h\" 1 3 4\n"
"# 32 \"/usr/include/libio.h\" 3 4\n"
"# 1 \"/usr/include/_G_config.h\" 1 3 4\n"
"# 15 \"/usr/include/_G_config.h\" 3 4\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 1 3 4\n"
"# 16 \"/usr/include/_G_config.h\" 2 3 4\n"
"# 1 \"/usr/include/wchar.h\" 1 3 4\n"
"# 83 \"/usr/include/wchar.h\" 3 4\n"
"typedef struct\n"
"{\n"
"  int __count;\n"
"  union\n"
"  {\n"
"    unsigned int __wch;\n"
"    char __wchb[4];\n"
"  } __value;\n"
"} __mbstate_t;\n"
"# 21 \"/usr/include/_G_config.h\" 2 3 4\n"
"typedef struct\n"
"{\n"
"  __off_t __pos;\n"
"  __mbstate_t __state;\n"
"} _G_fpos_t;\n"
"typedef struct\n"
"{\n"
"  __off64_t __pos;\n"
"  __mbstate_t __state;\n"
"} _G_fpos64_t;\n"
"# 53 \"/usr/include/_G_config.h\" 3 4\n"
"typedef int _G_int16_t __attribute__ ((__mode__ (__HI__)));\n"
"typedef int _G_int32_t __attribute__ ((__mode__ (__SI__)));\n"
"typedef unsigned int _G_uint16_t __attribute__ ((__mode__ (__HI__)));\n"
"typedef unsigned int _G_uint32_t __attribute__ ((__mode__ (__SI__)));\n"
"# 33 \"/usr/include/libio.h\" 2 3 4\n"
"# 53 \"/usr/include/libio.h\" 3 4\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdarg.h\" 1 3 4\n"
"# 40 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdarg.h\" 3 4\n"
"typedef __builtin_va_list __gnuc_va_list;\n"
"# 54 \"/usr/include/libio.h\" 2 3 4\n"
"# 170 \"/usr/include/libio.h\" 3 4\n"
"struct _IO_jump_t; struct _IO_FILE;\n"
"# 180 \"/usr/include/libio.h\" 3 4\n"
"typedef void _IO_lock_t;\n"
"struct _IO_marker {\n"
"  struct _IO_marker *_next;\n"
"  struct _IO_FILE *_sbuf;\n"
"  int _pos;\n"
"# 203 \"/usr/include/libio.h\" 3 4\n"
"};\n"
"enum __codecvt_result\n"
"{\n"
"  __codecvt_ok,\n"
"  __codecvt_partial,\n"
"  __codecvt_error,\n"
"  __codecvt_noconv\n"
"};\n"
"# 271 \"/usr/include/libio.h\" 3 4\n"
"struct _IO_FILE {\n"
"  int _flags;\n"
"  char* _IO_read_ptr;\n"
"  char* _IO_read_end;\n"
"  char* _IO_read_base;\n"
"  char* _IO_write_base;\n"
"  char* _IO_write_ptr;\n"
"  char* _IO_write_end;\n"
"  char* _IO_buf_base;\n"
"  char* _IO_buf_end;\n"
"  char *_IO_save_base;\n"
"  char *_IO_backup_base;\n"
"  char *_IO_save_end;\n"
"  struct _IO_marker *_markers;\n"
"  struct _IO_FILE *_chain;\n"
"  int _fileno;\n"
"  int _flags2;\n"
"  __off_t _old_offset;\n"
"  unsigned short _cur_column;\n"
"  signed char _vtable_offset;\n"
"  char _shortbuf[1];\n"
"  _IO_lock_t *_lock;\n"
"# 319 \"/usr/include/libio.h\" 3 4\n"
"  __off64_t _offset;\n"
"# 328 \"/usr/include/libio.h\" 3 4\n"
"  void *__pad1;\n"
"  void *__pad2;\n"
"  void *__pad3;\n"
"  void *__pad4;\n"
"  size_t __pad5;\n"
"  int _mode;\n"
"  char _unused2[15 * sizeof (int) - 4 * sizeof (void *) - sizeof (size_t)];\n"
"};\n"
"typedef struct _IO_FILE _IO_FILE;\n"
"struct _IO_FILE_plus;\n"
"extern struct _IO_FILE_plus _IO_2_1_stdin_;\n"
"extern struct _IO_FILE_plus _IO_2_1_stdout_;\n"
"extern struct _IO_FILE_plus _IO_2_1_stderr_;\n"
"# 364 \"/usr/include/libio.h\" 3 4\n"
"typedef __ssize_t __io_read_fn (void *__cookie, char *__buf, size_t __nbytes);\n"
"typedef __ssize_t __io_write_fn (void *__cookie, __const char *__buf,\n"
"     size_t __n);\n"
"typedef int __io_seek_fn (void *__cookie, __off64_t *__pos, int __w);\n"
"typedef int __io_close_fn (void *__cookie);\n"
"# 416 \"/usr/include/libio.h\" 3 4\n"
"extern int __underflow (_IO_FILE *);\n"
"extern int __uflow (_IO_FILE *);\n"
"extern int __overflow (_IO_FILE *, int);\n"
"# 460 \"/usr/include/libio.h\" 3 4\n"
"extern int _IO_getc (_IO_FILE *__fp);\n"
"extern int _IO_putc (int __c, _IO_FILE *__fp);\n"
"extern int _IO_feof (_IO_FILE *__fp) __attribute__ ((__nothrow__));\n"
"extern int _IO_ferror (_IO_FILE *__fp) __attribute__ ((__nothrow__));\n"
"extern int _IO_peekc_locked (_IO_FILE *__fp);\n"
"extern void _IO_flockfile (_IO_FILE *) __attribute__ ((__nothrow__));\n"
"extern void _IO_funlockfile (_IO_FILE *) __attribute__ ((__nothrow__));\n"
"extern int _IO_ftrylockfile (_IO_FILE *) __attribute__ ((__nothrow__));\n"
"# 490 \"/usr/include/libio.h\" 3 4\n"
"extern int _IO_vfscanf (_IO_FILE * __restrict, const char * __restrict,\n"
"   __gnuc_va_list, int *__restrict);\n"
"extern int _IO_vfprintf (_IO_FILE *__restrict, const char *__restrict,\n"
"    __gnuc_va_list);\n"
"extern __ssize_t _IO_padn (_IO_FILE *, int, __ssize_t);\n"
"extern size_t _IO_sgetn (_IO_FILE *, void *, size_t);\n"
"extern __off64_t _IO_seekoff (_IO_FILE *, __off64_t, int, int);\n"
"extern __off64_t _IO_seekpos (_IO_FILE *, __off64_t, int);\n"
"extern void _IO_free_backup_area (_IO_FILE *) __attribute__ ((__nothrow__));\n"
"# 76 \"/usr/include/stdio.h\" 2 3 4\n"
"typedef __gnuc_va_list va_list;\n"
"# 109 \"/usr/include/stdio.h\" 3 4\n"
"typedef _G_fpos_t fpos_t;\n"
"# 161 \"/usr/include/stdio.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/stdio_lim.h\" 1 3 4\n"
"# 162 \"/usr/include/stdio.h\" 2 3 4\n"
"extern struct _IO_FILE *stdin;\n"
"extern struct _IO_FILE *stdout;\n"
"extern struct _IO_FILE *stderr;\n"
"extern int remove (__const char *__filename) __attribute__ ((__nothrow__));\n"
"extern int rename (__const char *__old, __const char *__new) __attribute__ ((__nothrow__));\n"
"extern int renameat (int __oldfd, __const char *__old, int __newfd,\n"
"       __const char *__new) __attribute__ ((__nothrow__));\n"
"extern FILE *tmpfile (void) ;\n"
"# 206 \"/usr/include/stdio.h\" 3 4\n"
"extern char *tmpnam (char *__s) __attribute__ ((__nothrow__)) ;\n"
"extern char *tmpnam_r (char *__s) __attribute__ ((__nothrow__)) ;\n"
"# 224 \"/usr/include/stdio.h\" 3 4\n"
"extern char *tempnam (__const char *__dir, __const char *__pfx)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__malloc__)) ;\n"
"extern int fclose (FILE *__stream);\n"
"extern int fflush (FILE *__stream);\n"
"# 249 \"/usr/include/stdio.h\" 3 4\n"
"extern int fflush_unlocked (FILE *__stream);\n"
"# 263 \"/usr/include/stdio.h\" 3 4\n"
"extern FILE *fopen (__const char *__restrict __filename,\n"
"      __const char *__restrict __modes) ;\n"
"extern FILE *freopen (__const char *__restrict __filename,\n"
"        __const char *__restrict __modes,\n"
"        FILE *__restrict __stream) ;\n"
"# 292 \"/usr/include/stdio.h\" 3 4\n"
"# 303 \"/usr/include/stdio.h\" 3 4\n"
"extern FILE *fdopen (int __fd, __const char *__modes) __attribute__ ((__nothrow__)) ;\n"
"# 316 \"/usr/include/stdio.h\" 3 4\n"
"extern FILE *fmemopen (void *__s, size_t __len, __const char *__modes)\n"
"  __attribute__ ((__nothrow__)) ;\n"
"extern FILE *open_memstream (char **__bufloc, size_t *__sizeloc) __attribute__ ((__nothrow__)) ;\n"
"extern void setbuf (FILE *__restrict __stream, char *__restrict __buf) __attribute__ ((__nothrow__));\n"
"extern int setvbuf (FILE *__restrict __stream, char *__restrict __buf,\n"
"      int __modes, size_t __n) __attribute__ ((__nothrow__));\n"
"extern void setbuffer (FILE *__restrict __stream, char *__restrict __buf,\n"
"         size_t __size) __attribute__ ((__nothrow__));\n"
"extern void setlinebuf (FILE *__stream) __attribute__ ((__nothrow__));\n"
"extern int fprintf (FILE *__restrict __stream,\n"
"      __const char *__restrict __format, ...);\n"
"extern int printf (__const char *__restrict __format, ...);\n"
"extern int sprintf (char *__restrict __s,\n"
"      __const char *__restrict __format, ...) __attribute__ ((__nothrow__));\n"
"extern int vfprintf (FILE *__restrict __s, __const char *__restrict __format,\n"
"       __gnuc_va_list __arg);\n"
"extern int vprintf (__const char *__restrict __format, __gnuc_va_list __arg);\n"
"extern int vsprintf (char *__restrict __s, __const char *__restrict __format,\n"
"       __gnuc_va_list __arg) __attribute__ ((__nothrow__));\n"
"extern int snprintf (char *__restrict __s, size_t __maxlen,\n"
"       __const char *__restrict __format, ...)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__format__ (__printf__, 3, 4)));\n"
"extern int vsnprintf (char *__restrict __s, size_t __maxlen,\n"
"        __const char *__restrict __format, __gnuc_va_list __arg)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__format__ (__printf__, 3, 0)));\n"
"# 414 \"/usr/include/stdio.h\" 3 4\n"
"extern int vdprintf (int __fd, __const char *__restrict __fmt,\n"
"       __gnuc_va_list __arg)\n"
"     __attribute__ ((__format__ (__printf__, 2, 0)));\n"
"extern int dprintf (int __fd, __const char *__restrict __fmt, ...)\n"
"     __attribute__ ((__format__ (__printf__, 2, 3)));\n"
"extern int fscanf (FILE *__restrict __stream,\n"
"     __const char *__restrict __format, ...) ;\n"
"extern int scanf (__const char *__restrict __format, ...) ;\n"
"extern int sscanf (__const char *__restrict __s,\n"
"     __const char *__restrict __format, ...) __attribute__ ((__nothrow__));\n"
"# 445 \"/usr/include/stdio.h\" 3 4\n"
"extern int fscanf (FILE *__restrict __stream, __const char *__restrict __format, ...) __asm__ (\"\" \"__isoc99_fscanf\")\n"
"                               ;\n"
"extern int scanf (__const char *__restrict __format, ...) __asm__ (\"\" \"__isoc99_scanf\")\n"
"                              ;\n"
"extern int sscanf (__const char *__restrict __s, __const char *__restrict __format, ...) __asm__ (\"\" \"__isoc99_sscanf\") __attribute__ ((__nothrow__))\n"
"                      ;\n"
"# 465 \"/usr/include/stdio.h\" 3 4\n"
"extern int vfscanf (FILE *__restrict __s, __const char *__restrict __format,\n"
"      __gnuc_va_list __arg)\n"
"     __attribute__ ((__format__ (__scanf__, 2, 0))) ;\n"
"extern int vscanf (__const char *__restrict __format, __gnuc_va_list __arg)\n"
"     __attribute__ ((__format__ (__scanf__, 1, 0))) ;\n"
"extern int vsscanf (__const char *__restrict __s,\n"
"      __const char *__restrict __format, __gnuc_va_list __arg)\n"
"     __attribute__ ((__nothrow__)) __attribute__ ((__format__ (__scanf__, 2, 0)));\n"
"# 496 \"/usr/include/stdio.h\" 3 4\n"
"extern int vfscanf (FILE *__restrict __s, __const char *__restrict __format, __gnuc_va_list __arg) __asm__ (\"\" \"__isoc99_vfscanf\")\n"
"     __attribute__ ((__format__ (__scanf__, 2, 0))) ;\n"
"extern int vscanf (__const char *__restrict __format, __gnuc_va_list __arg) __asm__ (\"\" \"__isoc99_vscanf\")\n"
"     __attribute__ ((__format__ (__scanf__, 1, 0))) ;\n"
"extern int vsscanf (__const char *__restrict __s, __const char *__restrict __format, __gnuc_va_list __arg) __asm__ (\"\" \"__isoc99_vsscanf\") __attribute__ ((__nothrow__))\n"
"     __attribute__ ((__format__ (__scanf__, 2, 0)));\n"
"# 524 \"/usr/include/stdio.h\" 3 4\n"
"extern int fgetc (FILE *__stream);\n"
"extern int getc (FILE *__stream);\n"
"extern int getchar (void);\n"
"# 552 \"/usr/include/stdio.h\" 3 4\n"
"extern int getc_unlocked (FILE *__stream);\n"
"extern int getchar_unlocked (void);\n"
"# 563 \"/usr/include/stdio.h\" 3 4\n"
"extern int fgetc_unlocked (FILE *__stream);\n"
"extern int fputc (int __c, FILE *__stream);\n"
"extern int putc (int __c, FILE *__stream);\n"
"extern int putchar (int __c);\n"
"# 596 \"/usr/include/stdio.h\" 3 4\n"
"extern int fputc_unlocked (int __c, FILE *__stream);\n"
"extern int putc_unlocked (int __c, FILE *__stream);\n"
"extern int putchar_unlocked (int __c);\n"
"extern int getw (FILE *__stream);\n"
"extern int putw (int __w, FILE *__stream);\n"
"extern char *fgets (char *__restrict __s, int __n, FILE *__restrict __stream)\n"
"     ;\n"
"extern char *gets (char *__s) ;\n"
"# 658 \"/usr/include/stdio.h\" 3 4\n"
"extern __ssize_t __getdelim (char **__restrict __lineptr,\n"
"          size_t *__restrict __n, int __delimiter,\n"
"          FILE *__restrict __stream) ;\n"
"extern __ssize_t getdelim (char **__restrict __lineptr,\n"
"        size_t *__restrict __n, int __delimiter,\n"
"        FILE *__restrict __stream) ;\n"
"extern __ssize_t getline (char **__restrict __lineptr,\n"
"       size_t *__restrict __n,\n"
"       FILE *__restrict __stream) ;\n"
"extern int fputs (__const char *__restrict __s, FILE *__restrict __stream);\n"
"extern int puts (__const char *__s);\n"
"extern int ungetc (int __c, FILE *__stream);\n"
"extern size_t fread (void *__restrict __ptr, size_t __size,\n"
"       size_t __n, FILE *__restrict __stream) ;\n"
"extern size_t fwrite (__const void *__restrict __ptr, size_t __size,\n"
"        size_t __n, FILE *__restrict __s);\n"
"# 730 \"/usr/include/stdio.h\" 3 4\n"
"extern size_t fread_unlocked (void *__restrict __ptr, size_t __size,\n"
"         size_t __n, FILE *__restrict __stream) ;\n"
"extern size_t fwrite_unlocked (__const void *__restrict __ptr, size_t __size,\n"
"          size_t __n, FILE *__restrict __stream);\n"
"extern int fseek (FILE *__stream, long int __off, int __whence);\n"
"extern long int ftell (FILE *__stream) ;\n"
"extern void rewind (FILE *__stream);\n"
"# 766 \"/usr/include/stdio.h\" 3 4\n"
"extern int fseeko (FILE *__stream, __off_t __off, int __whence);\n"
"extern __off_t ftello (FILE *__stream) ;\n"
"# 785 \"/usr/include/stdio.h\" 3 4\n"
"extern int fgetpos (FILE *__restrict __stream, fpos_t *__restrict __pos);\n"
"extern int fsetpos (FILE *__stream, __const fpos_t *__pos);\n"
"# 808 \"/usr/include/stdio.h\" 3 4\n"
"# 817 \"/usr/include/stdio.h\" 3 4\n"
"extern void clearerr (FILE *__stream) __attribute__ ((__nothrow__));\n"
"extern int feof (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern int ferror (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern void clearerr_unlocked (FILE *__stream) __attribute__ ((__nothrow__));\n"
"extern int feof_unlocked (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern int ferror_unlocked (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern void perror (__const char *__s);\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/sys_errlist.h\" 1 3 4\n"
"# 27 \"/usr/include/x86_64-linux-gnu/bits/sys_errlist.h\" 3 4\n"
"extern int sys_nerr;\n"
"extern __const char *__const sys_errlist[];\n"
"# 847 \"/usr/include/stdio.h\" 2 3 4\n"
"extern int fileno (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern int fileno_unlocked (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"# 866 \"/usr/include/stdio.h\" 3 4\n"
"extern FILE *popen (__const char *__command, __const char *__modes) ;\n"
"extern int pclose (FILE *__stream);\n"
"extern char *ctermid (char *__s) __attribute__ ((__nothrow__));\n"
"# 906 \"/usr/include/stdio.h\" 3 4\n"
"extern void flockfile (FILE *__stream) __attribute__ ((__nothrow__));\n"
"extern int ftrylockfile (FILE *__stream) __attribute__ ((__nothrow__)) ;\n"
"extern void funlockfile (FILE *__stream) __attribute__ ((__nothrow__));\n"
"# 936 \"/usr/include/stdio.h\" 3 4\n"
"# 24 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\" 2\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdint.h\" 1 3 4\n"
"# 1 \"/usr/include/stdint.h\" 1 3 4\n"
"# 27 \"/usr/include/stdint.h\" 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wchar.h\" 1 3 4\n"
"# 28 \"/usr/include/stdint.h\" 2 3 4\n"
"# 1 \"/usr/include/x86_64-linux-gnu/bits/wordsize.h\" 1 3 4\n"
"# 29 \"/usr/include/stdint.h\" 2 3 4\n"
"# 37 \"/usr/include/stdint.h\" 3 4\n"
"typedef signed char int8_t;\n"
"typedef short int int16_t;\n"
"typedef int int32_t;\n"
"typedef long int int64_t;\n"
"typedef unsigned char uint8_t;\n"
"typedef unsigned short int uint16_t;\n"
"typedef unsigned int uint32_t;\n"
"typedef unsigned long int uint64_t;\n"
"# 66 \"/usr/include/stdint.h\" 3 4\n"
"typedef signed char int_least8_t;\n"
"typedef short int int_least16_t;\n"
"typedef int int_least32_t;\n"
"typedef long int int_least64_t;\n"
"typedef unsigned char uint_least8_t;\n"
"typedef unsigned short int uint_least16_t;\n"
"typedef unsigned int uint_least32_t;\n"
"typedef unsigned long int uint_least64_t;\n"
"# 91 \"/usr/include/stdint.h\" 3 4\n"
"typedef signed char int_fast8_t;\n"
"typedef long int int_fast16_t;\n"
"typedef long int int_fast32_t;\n"
"typedef long int int_fast64_t;\n"
"# 104 \"/usr/include/stdint.h\" 3 4\n"
"typedef unsigned char uint_fast8_t;\n"
"typedef unsigned long int uint_fast16_t;\n"
"typedef unsigned long int uint_fast32_t;\n"
"typedef unsigned long int uint_fast64_t;\n"
"# 123 \"/usr/include/stdint.h\" 3 4\n"
"typedef unsigned long int uintptr_t;\n"
"# 135 \"/usr/include/stdint.h\" 3 4\n"
"typedef long int intmax_t;\n"
"typedef unsigned long int uintmax_t;\n"
"# 4 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdint.h\" 2 3 4\n"
"# 25 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\" 2\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 1 3 4\n"
"# 150 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 3 4\n"
"typedef long int ptrdiff_t;\n"
"# 324 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h\" 3 4\n"
"typedef int wchar_t;\n"
"# 26 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\" 2\n"
"# 1 \"/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdbool.h\" 1 3 4\n"
"# 27 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\" 2\n"
"typedef struct {\n"
"   void **address;\n"
"   ptrdiff_t offset;\n"
"   struct {\n"
"     _Bool input: 1;\n"
"     _Bool output: 1;\n"
"     _Bool can_rename:1;\n"
"     _Bool commutative: 1;\n"
"   } flags;\n"
"   size_t size;\n"
"} nanos_dependence_internal_t;\n"
"typedef enum {\n"
"   NANOS_PRIVATE,\n"
"   NANOS_SHARED,\n"
"} nanos_sharing_t;\n"
"typedef struct {\n"
"   uint64_t address;\n"
"   nanos_sharing_t sharing;\n"
"   struct {\n"
"      _Bool input: 1;\n"
"      _Bool output: 1;\n"
"   } flags;\n"
"   size_t size;\n"
"} nanos_copy_data_internal_t;\n"
"typedef nanos_dependence_internal_t nanos_dependence_t;\n"
"typedef nanos_copy_data_internal_t nanos_copy_data_t;\n"
"# 78 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos-int.h\"\n"
"typedef void * nanos_thread_t;\n"
"typedef void * nanos_wd_t;\n"
"typedef struct {\n"
"   int nsect;\n"
"   nanos_wd_t lwd[];\n"
"} nanos_compound_wd_data_t;\n"
"typedef struct {\n"
"   int n;\n"
"} nanos_repeat_n_info_t;\n"
"typedef struct {\n"
"   int lower;\n"
"   int upper;\n"
"   int step;\n"
"   _Bool last;\n"
"   int chunk;\n"
"   int stride;\n"
"   void *args;\n"
"} nanos_loop_info_t;\n"
"typedef struct {\n"
"   _Bool mandatory_creation:1;\n"
"   _Bool tied:1;\n"
"   _Bool reserved0:1;\n"
"   _Bool reserved1:1;\n"
"   _Bool reserved2:1;\n"
"   _Bool reserved3:1;\n"
"   _Bool reserved4:1;\n"
"   _Bool reserved5:1;\n"
"   nanos_thread_t tie_to;\n"
"   unsigned int priority;\n"
"} nanos_wd_props_t;\n"
"typedef struct {\n"
"  void * (*factory) (void *prealloc, void *arg);\n"
"  size_t dd_size;\n"
"  void * arg;\n"
"} nanos_device_t;\n"
"typedef enum { NANOS_STATE_START, NANOS_STATE_END, NANOS_SUBSTATE_START, NANOS_SUBSTATE_END,\n"
"               NANOS_BURST_START, NANOS_BURST_END, NANOS_PTP_START, NANOS_PTP_END, NANOS_POINT, EVENT_TYPES\n"
"} nanos_event_type_t;\n"
"typedef enum { NANOS_NOT_CREATED, NANOS_NOT_TRACED, NANOS_STARTUP, NANOS_SHUTDOWN, NANOS_ERROR, NANOS_IDLE,\n"
"               NANOS_RUNTIME, NANOS_RUNNING, NANOS_SYNCHRONIZATION, NANOS_SCHEDULING, NANOS_CREATION,\n"
"               NANOS_MEM_TRANSFER_IN, NANOS_MEM_TRANSFER_OUT, NANOS_MEM_TRANSFER_LOCAL,\n"
"               NANOS_MEM_TRANSFER_DEVICE_IN, NANOS_MEM_TRANSFER_DEVICE_OUT, NANOS_MEM_TRANSFER_DEVICE_LOCAL,\n"
"               NANOS_CACHE, NANOS_YIELD, NANOS_EVENT_STATE_TYPES\n"
"} nanos_event_state_value_t;\n"
"typedef enum { NANOS_WD_DOMAIN, NANOS_WD_DEPENDENCY, NANOS_WAIT, NANOS_WD_REMOTE, NANOS_XFER_PUT, NANOS_XFER_GET } nanos_event_domain_t;\n"
"typedef long long nanos_event_id_t;\n"
"typedef unsigned int nanos_event_key_t;\n"
"typedef unsigned long long nanos_event_value_t;\n"
"typedef struct {\n"
"   nanos_event_key_t key;\n"
"   nanos_event_value_t value;\n"
"} nanos_event_burst_t;\n"
"typedef struct {\n"
"   nanos_event_state_value_t value;\n"
"} nanos_event_state_t;\n"
"typedef struct {\n"
"   unsigned int nkvs;\n"
"   nanos_event_key_t *keys;\n"
"   nanos_event_value_t *values;\n"
"} nanos_event_point_t;\n"
"typedef struct {\n"
"   nanos_event_domain_t domain;\n"
"   nanos_event_id_t id;\n"
"   unsigned int nkvs;\n"
"   nanos_event_key_t *keys;\n"
"   nanos_event_value_t *values;\n"
"} nanos_event_ptp_t;\n"
"typedef struct {\n"
"   nanos_event_type_t type;\n"
"   union {\n"
"      nanos_event_burst_t burst;\n"
"      nanos_event_state_t state;\n"
"      nanos_event_point_t point;\n"
"      nanos_event_ptp_t ptp;\n"
"   } info;\n"
"} nanos_event_t;\n"
"typedef enum { NANOS_LOCK_FREE = 0, NANOS_LOCK_BUSY = 1 } nanos_lock_state_t;\n"
"typedef struct nanos_lock_t {\n"
"   volatile nanos_lock_state_t _state;\n"
"} nanos_lock_t;\n"
"typedef void (* nanos_translate_args_t) (void *, nanos_wd_t);\n"
"typedef void (nanos_init_func_t) ( void * );\n"
"typedef struct {\n"
"   nanos_init_func_t *func;\n"
"   void *data;\n"
"} nanos_init_desc_t;\n"
"# 25 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\" 2\n"
"# 38 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"typedef void * nanos_wg_t;\n"
"typedef void * nanos_team_t;\n"
"typedef void * nanos_sched_t;\n"
"typedef void * nanos_slicer_t;\n"
"typedef void * nanos_dd_t;\n"
"typedef void * nanos_sync_cond_t;\n"
"typedef unsigned int nanos_copy_id_t;\n"
"typedef struct {\n"
"   int nthreads;\n"
"   void *arch;\n"
"} nanos_constraint_t;\n"
"typedef enum { NANOS_OK=0,\n"
"               NANOS_UNKNOWN_ERR,\n"
"               NANOS_UNIMPLEMENTED,\n"
"} nanos_err_t;\n"
"typedef struct {\n"
"   void (*outline) (void *);\n"
"} nanos_smp_args_t;\n"
"# 79 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"extern nanos_wd_t nanos_current_wd_ (void); extern nanos_wd_t nanos_current_wd (void);\n"
"extern int nanos_get_wd_id_ (nanos_wd_t wd); extern int nanos_get_wd_id (nanos_wd_t wd);\n"
"extern nanos_slicer_t nanos_find_slicer_ ( const char * slicer ); extern nanos_slicer_t nanos_find_slicer ( const char * slicer );\n"
"extern nanos_err_t\n"
" nanos_create_wd_\n"
"# 86 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" ( nanos_wd_t *wd, size_t num_devices, nanos_device_t *devices, size_t data_size, int data_align, void ** data, nanos_wg_t wg, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t **copies ); extern nanos_err_t nanos_create_wd ( nanos_wd_t *wd, size_t num_devices, nanos_device_t *devices, size_t data_size, int data_align, void ** data, nanos_wg_t wg, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t **copies )\n"
"                                                                                                                                    ;\n"
"extern nanos_err_t nanos_set_translate_function_ ( nanos_wd_t wd, nanos_translate_args_t translate_args ); extern nanos_err_t nanos_set_translate_function ( nanos_wd_t wd, nanos_translate_args_t translate_args );\n"
"extern nanos_err_t\n"
" nanos_create_sliced_wd_\n"
"# 91 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" ( nanos_wd_t *uwd, size_t num_devices, nanos_device_t *devices, size_t outline_data_size, int outline_data_align, void **outline_data, nanos_wg_t uwg, nanos_slicer_t slicer, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t **copies ); extern nanos_err_t nanos_create_sliced_wd ( nanos_wd_t *uwd, size_t num_devices, nanos_device_t *devices, size_t outline_data_size, int outline_data_align, void **outline_data, nanos_wg_t uwg, nanos_slicer_t slicer, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t **copies )\n"
"                                                                                                              ;\n"
"extern nanos_err_t nanos_submit_ ( nanos_wd_t wd, size_t num_deps, nanos_dependence_t *deps, nanos_team_t team ); extern nanos_err_t nanos_submit ( nanos_wd_t wd, size_t num_deps, nanos_dependence_t *deps, nanos_team_t team );\n"
"extern nanos_err_t\n"
" nanos_create_wd_and_run_\n"
"# 98 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" ( size_t num_devices, nanos_device_t *devices, size_t data_size, int data_align, void * data, size_t num_deps, nanos_dependence_t *deps, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t *copies, nanos_translate_args_t translate_args ); extern nanos_err_t nanos_create_wd_and_run ( size_t num_devices, nanos_device_t *devices, size_t data_size, int data_align, void * data, size_t num_deps, nanos_dependence_t *deps, nanos_wd_props_t *props, size_t num_copies, nanos_copy_data_t *copies, nanos_translate_args_t translate_args )\n"
"                                                                                                                            ;\n"
"extern nanos_err_t nanos_create_for_ ( void ); extern nanos_err_t nanos_create_for ( void );\n"
"extern nanos_err_t nanos_set_internal_wd_data_ ( nanos_wd_t wd, void *data ); extern nanos_err_t nanos_set_internal_wd_data ( nanos_wd_t wd, void *data );\n"
"extern nanos_err_t nanos_get_internal_wd_data_ ( nanos_wd_t wd, void **data ); extern nanos_err_t nanos_get_internal_wd_data ( nanos_wd_t wd, void **data );\n"
"extern nanos_err_t nanos_yield_ ( void ); extern nanos_err_t nanos_yield ( void );\n"
"extern nanos_err_t nanos_slicer_get_specific_data_ ( nanos_slicer_t slicer, void ** data ); extern nanos_err_t nanos_slicer_get_specific_data ( nanos_slicer_t slicer, void ** data );\n"
"extern nanos_err_t\n"
" nanos_create_team_\n"
"# 112 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" (nanos_team_t *team, nanos_sched_t sg, unsigned int *nthreads, nanos_constraint_t * constraints, _Bool reuse, nanos_thread_t *info); extern nanos_err_t nanos_create_team (nanos_team_t *team, nanos_sched_t sg, unsigned int *nthreads, nanos_constraint_t * constraints, _Bool reuse, nanos_thread_t *info)\n"
"                                                                                                  ;\n"
"extern nanos_err_t nanos_create_team_mapped_ (nanos_team_t *team, nanos_sched_t sg, unsigned int *nthreads, unsigned int *mapping); extern nanos_err_t nanos_create_team_mapped (nanos_team_t *team, nanos_sched_t sg, unsigned int *nthreads, unsigned int *mapping);\n"
"extern nanos_err_t nanos_leave_team_ ( ); extern nanos_err_t nanos_leave_team ( );\n"
"extern nanos_err_t nanos_end_team_ ( nanos_team_t team ); extern nanos_err_t nanos_end_team ( nanos_team_t team );\n"
"extern nanos_err_t nanos_team_barrier_ ( void ); extern nanos_err_t nanos_team_barrier ( void );\n"
"extern nanos_err_t nanos_single_guard_ ( _Bool *); extern nanos_err_t nanos_single_guard ( _Bool *);\n"
"extern nanos_err_t nanos_wg_wait_completion_ ( nanos_wg_t wg, _Bool avoid_flush ); extern nanos_err_t nanos_wg_wait_completion ( nanos_wg_t wg, _Bool avoid_flush );\n"
"extern nanos_err_t nanos_create_int_sync_cond_ ( nanos_sync_cond_t *sync_cond, volatile int *p, int condition ); extern nanos_err_t nanos_create_int_sync_cond ( nanos_sync_cond_t *sync_cond, volatile int *p, int condition );\n"
"extern nanos_err_t nanos_create_bool_sync_cond_ ( nanos_sync_cond_t *sync_cond, volatile _Bool *p, _Bool condition ); extern nanos_err_t nanos_create_bool_sync_cond ( nanos_sync_cond_t *sync_cond, volatile _Bool *p, _Bool condition );\n"
"extern nanos_err_t nanos_sync_cond_wait_ ( nanos_sync_cond_t *sync_cond ); extern nanos_err_t nanos_sync_cond_wait ( nanos_sync_cond_t *sync_cond );\n"
"extern nanos_err_t nanos_sync_cond_signal_ ( nanos_sync_cond_t *sync_cond ); extern nanos_err_t nanos_sync_cond_signal ( nanos_sync_cond_t *sync_cond );\n"
"extern nanos_err_t nanos_destroy_sync_cond_ ( nanos_sync_cond_t *sync_cond ); extern nanos_err_t nanos_destroy_sync_cond ( nanos_sync_cond_t *sync_cond );\n"
"extern nanos_err_t nanos_wait_on_ ( size_t num_deps, nanos_dependence_t *deps ); extern nanos_err_t nanos_wait_on ( size_t num_deps, nanos_dependence_t *deps );\n"
"extern nanos_err_t nanos_init_lock_ ( nanos_lock_t **lock ); extern nanos_err_t nanos_init_lock ( nanos_lock_t **lock );\n"
"extern nanos_err_t nanos_set_lock_ (nanos_lock_t *lock); extern nanos_err_t nanos_set_lock (nanos_lock_t *lock);\n"
"extern nanos_err_t nanos_unset_lock_ (nanos_lock_t *lock); extern nanos_err_t nanos_unset_lock (nanos_lock_t *lock);\n"
"extern nanos_err_t nanos_try_lock_ ( nanos_lock_t *lock, _Bool *result ); extern nanos_err_t nanos_try_lock ( nanos_lock_t *lock, _Bool *result );\n"
"extern nanos_err_t nanos_destroy_lock_ ( nanos_lock_t *lock ); extern nanos_err_t nanos_destroy_lock ( nanos_lock_t *lock );\n"
"extern nanos_err_t nanos_get_addr_ ( nanos_copy_id_t copy_id, void **addr, nanos_wd_t cwd ); extern nanos_err_t nanos_get_addr ( nanos_copy_id_t copy_id, void **addr, nanos_wd_t cwd );\n"
"extern nanos_err_t nanos_copy_value_ ( void *dst, nanos_copy_id_t copy_id, nanos_wd_t cwd ); extern nanos_err_t nanos_copy_value ( void *dst, nanos_copy_id_t copy_id, nanos_wd_t cwd );\n"
"extern nanos_err_t nanos_get_num_running_tasks_ ( int *num ); extern nanos_err_t nanos_get_num_running_tasks ( int *num );\n"
"extern void nanos_handle_error_ ( nanos_err_t err ); extern void nanos_handle_error ( nanos_err_t err );\n"
"extern void * nanos_smp_factory_ ( void *prealloc ,void *args); extern void * nanos_smp_factory ( void *prealloc ,void *args);\n"
"extern const size_t nanos_smp_dd_size;\n"
"extern void * nanos_gpu_factory_ ( void *prealloc ,void *args); extern void * nanos_gpu_factory ( void *prealloc ,void *args);\n"
"extern const size_t nanos_gpu_dd_size;\n"
"# 175 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
"extern nanos_err_t nanos_instrument_register_key_ ( nanos_event_key_t *event_key, const char *key, const char *description, _Bool abort_when_registered ); extern nanos_err_t nanos_instrument_register_key ( nanos_event_key_t *event_key, const char *key, const char *description, _Bool abort_when_registered );\n"
"extern nanos_err_t nanos_instrument_register_value_ ( nanos_event_value_t *event_value, const char *key, const char *value, const char *description, _Bool abort_when_registered ); extern nanos_err_t nanos_instrument_register_value ( nanos_event_value_t *event_value, const char *key, const char *value, const char *description, _Bool abort_when_registered );\n"
"extern nanos_err_t nanos_instrument_register_value_with_val_ ( nanos_event_value_t val, const char *key, const char *value, const char *description, _Bool abort_when_registered ); extern nanos_err_t nanos_instrument_register_value_with_val ( nanos_event_value_t val, const char *key, const char *value, const char *description, _Bool abort_when_registered );\n"
"extern nanos_err_t nanos_instrument_get_key_ (const char *key, nanos_event_key_t *event_key); extern nanos_err_t nanos_instrument_get_key (const char *key, nanos_event_key_t *event_key);\n"
"extern nanos_err_t nanos_instrument_get_value_ (const char *key, const char *value, nanos_event_value_t *event_value); extern nanos_err_t nanos_instrument_get_value (const char *key, const char *value, nanos_event_value_t *event_value);\n"
"extern nanos_err_t nanos_instrument_events_ ( unsigned int num_events, nanos_event_t events[] ); extern nanos_err_t nanos_instrument_events ( unsigned int num_events, nanos_event_t events[] );\n"
"extern nanos_err_t nanos_instrument_enter_state_ ( nanos_event_state_value_t state ); extern nanos_err_t nanos_instrument_enter_state ( nanos_event_state_value_t state );\n"
"extern nanos_err_t nanos_instrument_leave_state_ ( void ); extern nanos_err_t nanos_instrument_leave_state ( void );\n"
"extern nanos_err_t nanos_instrument_enter_burst_ ( nanos_event_key_t key, nanos_event_value_t value ); extern nanos_err_t nanos_instrument_enter_burst ( nanos_event_key_t key, nanos_event_value_t value );\n"
"extern nanos_err_t nanos_instrument_leave_burst_ ( nanos_event_key_t key ); extern nanos_err_t nanos_instrument_leave_burst ( nanos_event_key_t key );\n"
"extern nanos_err_t nanos_instrument_point_event_ ( unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values ); extern nanos_err_t nanos_instrument_point_event ( unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values );\n"
"extern nanos_err_t\n"
" nanos_instrument_ptp_start_\n"
"# 190 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" ( nanos_event_domain_t domain, nanos_event_id_t id, unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values ); extern nanos_err_t nanos_instrument_ptp_start ( nanos_event_domain_t domain, nanos_event_id_t id, unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values )\n"
"                                                                                                                   ;\n"
"extern nanos_err_t\n"
" nanos_instrument_ptp_end_\n"
"# 192 \"/home/roger/Compiladors/nanox/nanox-install/include/nanox/nanos.h\"\n"
" ( nanos_event_domain_t domain, nanos_event_id_t id, unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values ); extern nanos_err_t nanos_instrument_ptp_end ( nanos_event_domain_t domain, nanos_event_id_t id, unsigned int nkvs, nanos_event_key_t *keys, nanos_event_value_t *values )\n"
"                                                                                                                   ;\n"
"extern nanos_err_t nanos_instrument_disable_state_events_ ( nanos_event_state_value_t state ); extern nanos_err_t nanos_instrument_disable_state_events ( nanos_event_state_value_t state );\n"
"extern nanos_err_t nanos_instrument_enable_state_events_ ( void ); extern nanos_err_t nanos_instrument_enable_state_events ( void );\n"
"extern nanos_err_t nanos_instrument_close_user_fun_event_ ( void ); extern nanos_err_t nanos_instrument_close_user_fun_event ( void );\n"

;

    Source::source_language = SourceLanguage::C;

    Nodecl::NodeclBase new_tree = src.parse_global(top_level);

    Source::source_language = SourceLanguage::Current;
}

} }
