load_lib target.exp

set full_path_tool "../src/driver/mcxx"
# Reuse OpenMP tests
set testcases [lsort [find $srcdir/$subdir/../mcxx.openmp.dg *.cpp]]

send_user "\n"

# Mandatory for OpenMP tests
set wrapper_tool "../libtool"
source "${srcdir}/openmp_libs.conf"
append wrapper_options "--mode=execute "
set full_path_tool "../src/driver/mcxx"

foreach test $testcases {
    set basename_test [file tail $test]
    set dirname_test [file dirname $test]
    set rootname_test [file rootname $basename_test]
    set kind_of_test ""
    if [string match "success_*" $basename_test] {
        set kind_of_test "success"
    } elseif [string match "failure_*" $basename_test] {
        set kind_of_test "xfailure"
    } else {
        unresolved "$test"
        continue
    }

    send_user "Running test ${basename_test}...\n"

    set output_execution ""
    if {
        [catch { 
            set output_execution [eval exec $wrapper_tool $wrapper_options $full_path_tool \
                "--typecheck" "--variable=instrument:1" \
                "--config-file=./$subdir/config.mcxx" "--verbose" "--output-dir=." "-c" \
                "-o" "${rootname_test}.o" "$test" "|&" "cat"] 
        } output_execution ]
    } {
        if [expr { $kind_of_test == "xfailure" }] {
            pass "$test"
        } elseif [expr {$kind_of_test == "success"}] {
            fail "$test"
        } 
    } else {
        if [expr { $kind_of_test == "success" }] {
            pass "$test"
        } elseif [expr { $kind_of_test == "xfailure"} ] {
            xpass "$test"
        }
    }
    send_log "${output_execution}\n"

    exec "sh" "-c" "rm -f *mcxx_${basename_test} *${rootname_test}.o" 
}
