#!/bin/bash

##################################################################
# SETTINGS
# set path to clang-format binary

# Fallback case
if [ "$CLANG_FORMAT_DIFF" = none ];
then
    exit 0
fi

CLANG_FORMAT_DIFF=${CLANG_FORMAT_DIFF:=clang-format-diff}
CLANG_FORMAT_DIFF_PATH=$(which "$CLANG_FORMAT_DIFF")

if [ -z "${CLANG_FORMAT_DIFF_PATH}" \
    -o ! -e "${CLANG_FORMAT_DIFF_PATH}" \
    -o ! -x "${CLANG_FORMAT_DIFF_PATH}"  ];
then
    echo "Could not test format using '${CLANG_FORMAT_DIFF}'"
    echo "Set variable CLANG_FORMAT_DIFF to the proper clang-format-diff path"
    exit 1
fi

echo "Testing format..."

diffs=$(git diff --cached -U0 HEAD | "$CLANG_FORMAT_DIFF_PATH" -style file -p 1)

if [ -z "$diffs" ]
then
  echo "Format is OK"
  exit 0
else
  echo "Format is not OK"
  echo
  echo "$diffs"
  echo
  echo "Please fix it using clang-format"
  exit 1
fi
