#!/bin/bash

##################################################################
# SETTINGS
# set path to clang-format binary
CLANG_FORMAT_DIFF=${CLANG_FORMAT_DIFF:=clang-format-diff}

# Fallback case
if [ "$CLANG_FORMAT_DIFF" = none ];
then
    exit 0
fi

echo "Testing format..."

if [ ! -x $(which "$CLANG_FORMAT_DIFF") ];
then
    echo "Could not test format."
    echo "Set variable CLANG_FORMAT_DIFF to the proper clang-format-diff path"
    exit 1
fi

diffs=$(git diff --cached -U0 HEAD | $CLANG_FORMAT_DIFF -p 1)

if [ -z "$diffs" ]
then
  echo "Format is OK"
  exit 0
else
  echo "Format is not OK"
  echo
  echo "$diffs"
  echo
  echo "Please fix it using clang-format"
  exit 1
fi
