load_lib target.exp

source "$srcdir/config/mercurium.exp"

source "${srcdir}/hlt_libs.conf"

set testcases1 [lsort [find $srcdir/$subdir *.c]]
execute_testsuite_phases_profile $testcases1 $loaded_phases "hltcc" "--hlt --variable=allow_identity:false"

set testcases2 [lsort [find $srcdir/$subdir *.cpp]]
execute_testsuite_phases_profile $testcases2 $loaded_phases "hltcxx" "--hlt --variable=allow_identity:false"
