! <testinfo>
! test_generator=config/mercurium-ompss
! test_compile_fail_nanos6_mercurium=yes
! test_compile_fail_nanos6_imfc=yes
! </testinfo>
PROGRAM P
  IMPLICIT NONE
  INTEGER, PARAMETER :: STRL = 4
  CHARACTER(LEN=1), ALLOCATABLE :: V1(:)
  CHARACTER, ALLOCATABLE :: V2(:)
  CHARACTER(LEN=STRL), ALLOCATABLE :: V3(:)
  CHARACTER(LEN=STRL), ALLOCATABLE :: V4(:)
  CHARACTER, ALLOCATABLE :: V5(:,:)
  CHARACTER, ALLOCATABLE :: V6(:,:)
  CHARACTER(LEN=STRL), ALLOCATABLE :: V7(:,:)
  CHARACTER(LEN=STRL), ALLOCATABLE :: V8(:,:)

  ALLOCATE(V1(10))
  ALLOCATE(V2(10))
  ALLOCATE(V3(10))
  ALLOCATE(V4(10))

  ALLOCATE(V5(5,5))
  ALLOCATE(V6(5,5))
  ALLOCATE(V7(5,5))
  ALLOCATE(V8(5,5))
  !$OMP TASK INOUT(V1, V2(1:10), V3, V4(1:10), V5, V6(1:5, 1:5), V7, v8(1:5, 1:5))
  CONTINUE
  !$OMP END TASK

  !$OMP TASKWAIT

  DEALLOCATE(V1)
  DEALLOCATE(V2)
  DEALLOCATE(V3)
  DEALLOCATE(V4)
  DEALLOCATE(V5)
  DEALLOCATE(V6)
  DEALLOCATE(V7)
  DEALLOCATE(V8)

END PROGRAM P
