! <testinfo>
! test_generator=config/mercurium-omp
! </testinfo>
SUBROUTINE FOO(FUN, I)
    IMPLICIT NONE
    INTEGER :: I
    INTERFACE
        SUBROUTINE FUN(I)
            INTEGER :: I
        END SUBROUTINE FUN
    END INTERFACE

    !$OMP TASK
        CALL FUN(I)
    !$OMP END TASK
END SUBROUTINE FOO


SUBROUTINE BLA(I)
    IMPLICIT NONE
    INTEGER :: I
END SUBROUTINE BLA

PROGRAM P
IMPLICIT NONE
    INTERFACE
SUBROUTINE BLA(I)
    IMPLICIT NONE
    INTEGER :: I
END SUBROUTINE BLA
    END INTERFACE
    CALL FOO(BLA, 2)
END PROGRAM P
