! <testinfo>
! test_generator=config/mercurium-omp
! </testinfo>
MODULE M1
   TYPE T1
      INTEGER :: A
   END TYPE T1
   INTEGER, PARAMETER :: LENGTH = 1000
   TYPE(T1), DIMENSION(LENGTH) :: V
END MODULE M1

MODULE M2
   USE M1, ONLY: V, LENGTH
CONTAINS
  SUBROUTINE FOO
   IMPLICIT NONE
   INTEGER :: I
   !$OMP PARALLEL DO
   DO I=1, LENGTH
      V(I)%A = I
   ENDDO
  END SUBROUTINE FOO

  SUBROUTINE TEST
      CALL FOO()
   DO I=1, LENGTH
      IF (V(I)%A /= I) STOP 1
   ENDDO
  END SUBROUTINE TEST
END MODULE M2

PROGRAM MAIN
    USE M2, ONLY: TEST

    CALL TEST()
END PROGRAM MAIN
